#!/usr/bin/env python3
# SPDX-License-Identifier: Elastic-2.0

"""Standalone drift check for the parity-oracle boundary.

Three things can rot silently and none of them fail a test on their own:

1. `tools/oracle/vocabulary.md` is generated from the enumerations and the
   field registry. A stale copy is a document that describes a channel nobody
   is running;
2. `tools/oracle/runner.py` carries its own copy of four wire constants,
   because it has to travel to the custody host alone. A drifted copy makes
   every comparison refuse, which looks like a working boundary;
3. `tools/oracle/fields.json` is the registry the whole vocabulary is keyed to.

Run it standalone:

    python3 tools/oracle/check_boundary.py            # verify, write nothing
    python3 tools/oracle/check_boundary.py --write    # regenerate the document

Exit code is non-zero on drift, so it can be wired into `plan/check.py`. That
wiring is the integrator's follow-up: several items share that file this run
and this module is deliberately importable and self-contained so it can be
called from there without moving any logic.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import pathlib
import sys
import tempfile

if __package__ in (None, ""):  # standalone execution
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from tools.oracle import vocabulary as vocab

DOCUMENT = pathlib.Path(__file__).with_name("vocabulary.md")
RUNNER = pathlib.Path(__file__).with_name("runner.py")
GENERATED_BY = "tools/oracle/check_boundary.py"


def _table(header: tuple[str, ...], rows: list[tuple[str, ...]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return lines


def render_document(registry: vocab.Registry) -> str:
    """The vocabulary reference, derived entirely from the code and registry."""
    lines = [
        "<!-- SPDX-License-Identifier: Elastic-2.0 -->",
        "",
        "# Parity-oracle release vocabulary",
        "",
        f"GENERATED by `{GENERATED_BY}` — do not edit by hand.",
        "",
        "Every value below is a clean-side constant. A record from the custody",
        "side selects among them; it never supplies a string that is released.",
        "",
        "## Record shape",
        "",
        "```json",
        '{"schema":"' + vocab.RELEASE_SCHEMA + '",'
        '"outcome":"<outcome>","differences":[{"field":"<field>",'
        '"relation":"<relation>","magnitude":"<magnitude>"}]}',
        "```",
        "",
        f"At most **{vocab.RECORD_LIMIT}** bytes, exactly these three keys, no",
        "numbers, and no key or value outside the tables below.",
        "",
        "## Outcome",
        "",
    ]
    lines += _table(
        ("Value", "Differences", "Side"),
        [
            (
                outcome.value,
                "empty"
                if outcome in vocab.EMPTY_DIFFERENCES_REQUIRED
                else ("required" if outcome in vocab.DIFFERENCES_REQUIRED else "none"),
                "clean only" if outcome in vocab.CLEAN_SIDE_ONLY else "wire",
            )
            for outcome in vocab.Outcome
        ],
    )
    lines += ["", "## Relation", ""]
    lines += _table(("Value",), [(relation.value,) for relation in vocab.Relation])
    lines += ["", "## Magnitude", ""]
    lines += _table(("Value",), [(magnitude.value,) for magnitude in vocab.Magnitude])
    lines += ["", "## Refusal", ""]
    lines += _table(("Value",), [(refusal.value,) for refusal in vocab.Refusal])
    lines += ["", "## Release policy", ""]
    lines += _table(("Value",), [(policy.value,) for policy in vocab.ReleasePolicy])
    lines += ["", "## Field registry", ""]
    lines += _table(
        ("Field", "Area", "Masked", "Description"),
        [
            (field.field_id, field.area.value, str(field.masked).lower(), field.description)
            for field in registry.fields
        ],
    )
    lines += [
        "",
        "## Channel capacity",
        "",
        "The alphabet the custody side can choose from, per comparison. This is",
        "the residual covert-channel bound: a fully hostile custody process can",
        "signal this much and no more through the release channel.",
        "",
    ]
    lines += _table(
        ("Policy", "Distinct verdicts", "Bits per comparison"),
        [
            (
                policy.value,
                str(vocab.released_value_count(registry, policy)),
                f"{vocab.capacity_bits(registry, policy):.2f}",
            )
            for policy in vocab.ReleasePolicy
        ],
    )
    lines += [
        "",
        "Reduce it by shrinking the registry or by running under",
        "`outcome_only`. It is never zero, and this table is the reason that is",
        "stated rather than assumed.",
        "",
    ]
    return "\n".join(lines)


def load_runner() -> object:
    spec = importlib.util.spec_from_file_location("oracle_runner_constants", RUNNER)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load tools/oracle/runner.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def check_runner_constants() -> list[str]:
    runner = load_runner()
    problems = []
    expected = {
        "RELEASE_SCHEMA": vocab.RELEASE_SCHEMA,
        "RECORD_LIMIT": vocab.RECORD_LIMIT,
        "ERROR_OUTCOME": vocab.Outcome.ORACLE_ERROR.value,
        "REJECTED_OUTCOME": vocab.Outcome.INPUT_REJECTED.value,
    }
    for name, value in expected.items():
        actual = getattr(runner, name, None)
        if actual != value:
            problems.append(
                f"runner.py {name} has drifted from tools/oracle/vocabulary.py"
            )
    return problems


def write_atomically(path: pathlib.Path, text: str) -> None:
    """Stage beside the target, then rename. A reader never sees a half file."""
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=str(path.parent), prefix=path.name + ".", delete=False
    )
    try:
        with handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(handle.name, path)
    except BaseException:
        pathlib.Path(handle.name).unlink(missing_ok=True)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="regenerate the document")
    args = parser.parse_args(argv)

    try:
        registry = vocab.load_registry()
    except vocab.VocabularyError as exc:
        print(f"FAIL: field registry is not loadable: {exc}", file=sys.stderr)
        return 2

    expected = render_document(registry)
    if args.write:
        write_atomically(DOCUMENT, expected)
        print(f"wrote {DOCUMENT.name} ({len(expected)} bytes)")
        return 0

    problems = check_runner_constants()
    if not DOCUMENT.exists():
        problems.append("tools/oracle/vocabulary.md is missing")
    elif DOCUMENT.read_text(encoding="utf-8") != expected:
        problems.append(
            "tools/oracle/vocabulary.md is stale — regenerate with "
            "python3 tools/oracle/check_boundary.py --write"
        )
    for problem in problems:
        print(f"FAIL: {problem}", file=sys.stderr)
    if problems:
        print(f"\noracle boundary: {len(problems)} drift failure(s)", file=sys.stderr)
        return 1
    print(
        "ok — "
        f"{len(registry.fields)} registered field(s); capacity "
        f"{vocab.capacity_bits(registry, vocab.ReleasePolicy.FIELD_RELATIONS):.2f} "
        "bits per comparison under field_relations, "
        f"{vocab.capacity_bits(registry, vocab.ReleasePolicy.OUTCOME_ONLY):.2f} "
        "under outcome_only"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
