// SPDX-License-Identifier: Elastic-2.0

//! Normalized provider events, authority and cursor semantics.
//!
//! The central rule is that what was *shown* can never become what was
//! *decided*. Preview deltas and recorded events are separate types rather than
//! one type with an authority field a caller must remember to check, so terminal
//! reporting cannot accept a preview:
//!
//! First, the same construction that does compile, so the failure below cannot
//! be blamed on anything but the type it is meant to reject:
//!
//! ```
//! use automonique_protocol::event::{EventCoordinates, PreviewEvent};
//! use automonique_protocol::primitives::EpochMillis;
//! use automonique_protocol::provider::ProviderSessionId;
//!
//! let coordinates = EventCoordinates::new(
//!     ProviderSessionId::new("s-1").unwrap(), None, None,
//! );
//! let preview = PreviewEvent::new(1, coordinates, EpochMillis::from_millis(0), "partial");
//! assert_eq!(preview.text(), "partial");
//! ```
//!
//! Now the identical preview, offered to terminal reporting:
//!
//! ```compile_fail
//! use automonique_protocol::event::{EventCoordinates, PreviewEvent, RunTimeline};
//! use automonique_protocol::primitives::EpochMillis;
//! use automonique_protocol::provider::ProviderSessionId;
//!
//! let coordinates = EventCoordinates::new(
//!     ProviderSessionId::new("s-1").unwrap(), None, None,
//! );
//! let preview = PreviewEvent::new(1, coordinates, EpochMillis::from_millis(0), "partial");
//! let mut timeline = RunTimeline::new();
//! // Terminal reporting accepts recorded events only.
//! timeline.record(preview);
//! ```
//!
//! Nothing here connects to a provider, parses a vendor payload into its
//! vendor-specific shape, writes a journal or resolves an artifact.

use core::fmt;
use std::error::Error;

use crate::primitives::EpochMillis;
use crate::provider::{
    BinaryProvenance, ProviderItemId, ProviderRequestId, ProviderSessionId, ProviderTurnId,
};

/// Maximum bytes of provider payload carried inline in a raw record.
pub const MAX_INLINE_RAW_BYTES: usize = 64 * 1024;

/// Maximum UTF-8 byte length of a source event type or cursor.
pub const MAX_SOURCE_FIELD_BYTES: usize = 256;

/// How much a record may be relied upon.
///
/// Required on every recorded event; there is no default and no inferred value.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Authority {
    /// A completed provider message or reconciled history.
    Authoritative,
    /// Generated by Automonique rather than observed from a provider.
    Synthetic,
}

impl Authority {
    /// Stable lowercase wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Authoritative => "authoritative",
            Self::Synthetic => "synthetic",
        }
    }
}

/// The normalized event vocabulary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum EventKind {
    /// The runner reached the provider.
    ProviderConnected,
    /// The provider connection was lost.
    ProviderDisconnected,
    /// A new provider session exists.
    SessionCreated,
    /// An existing provider session was loaded.
    SessionLoaded,
    /// Session metadata changed.
    SessionUpdated,
    /// A turn was accepted but not started.
    TurnQueued,
    /// A turn began.
    TurnStarted,
    /// A running turn received steering input.
    TurnSteered,
    /// A running turn was interrupted.
    TurnInterrupted,
    /// A turn finished.
    TurnCompleted,
    /// An assistant message as it is still being written.
    ///
    /// The only kind that is preview by nature: it names text that was *shown*
    /// and may still change, so [`EventKind::is_preview_only`] holds for it and
    /// nothing else. A record of this kind is always [`Authority::Synthetic`],
    /// which is what stops a coalesced delta from being read as a decision.
    AssistantMessageDelta,
    /// An authoritative assistant message.
    AssistantMessageCompleted,
    /// A tool call began.
    ToolCallStarted,
    /// A tool call reported progress.
    ToolCallUpdated,
    /// A tool call finished.
    ToolCallCompleted,
    /// The provider asked for permission.
    ///
    /// The one wait an operator answers through the approval lane. Its label,
    /// when it carries one, names the durable approval and the tool that asked;
    /// see [`EventKind::text_rule`].
    ApprovalRequested,
    /// A permission request reached a decision.
    ApprovalResolved,
    /// The provider asked for input.
    ///
    /// A distinct kind rather than a second face of [`EventKind::ApprovalRequested`],
    /// because the two are answered through different authorities: an approval
    /// is decided by key through the approval lane, while provider input is
    /// delivered by whoever holds the session's controller lease. A renderer
    /// that drew both as one card would offer the wrong affordance for one of
    /// them. The turn is paused until the input arrives, exactly as it is for
    /// a permission request.
    InputRequested,
    /// A subagent began.
    SubagentStarted,
    /// A subagent reported an event.
    SubagentEvent,
    /// A subagent finished.
    SubagentCompleted,
    /// Usage or cost telemetry changed.
    UsageUpdated,
    /// The provider reported a recoverable problem.
    ProviderWarning,
    /// The provider reported a fault.
    ProviderFault,
    /// The run reached its single terminal state.
    RunTerminal,
}

impl EventKind {
    /// Every kind, for coverage checks.
    pub const ALL: [Self; 25] = [
        Self::ProviderConnected,
        Self::ProviderDisconnected,
        Self::SessionCreated,
        Self::SessionLoaded,
        Self::SessionUpdated,
        Self::TurnQueued,
        Self::TurnStarted,
        Self::TurnSteered,
        Self::TurnInterrupted,
        Self::TurnCompleted,
        Self::AssistantMessageDelta,
        Self::AssistantMessageCompleted,
        Self::ToolCallStarted,
        Self::ToolCallUpdated,
        Self::ToolCallCompleted,
        Self::ApprovalRequested,
        Self::ApprovalResolved,
        Self::InputRequested,
        Self::SubagentStarted,
        Self::SubagentEvent,
        Self::SubagentCompleted,
        Self::UsageUpdated,
        Self::ProviderWarning,
        Self::ProviderFault,
        Self::RunTerminal,
    ];

    /// Stable lowercase wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProviderConnected => "provider_connected",
            Self::ProviderDisconnected => "provider_disconnected",
            Self::SessionCreated => "session_created",
            Self::SessionLoaded => "session_loaded",
            Self::SessionUpdated => "session_updated",
            Self::TurnQueued => "turn_queued",
            Self::TurnStarted => "turn_started",
            Self::TurnSteered => "turn_steered",
            Self::TurnInterrupted => "turn_interrupted",
            Self::TurnCompleted => "turn_completed",
            Self::AssistantMessageDelta => "assistant_message_delta",
            Self::AssistantMessageCompleted => "assistant_message_completed",
            Self::ToolCallStarted => "tool_call_started",
            Self::ToolCallUpdated => "tool_call_updated",
            Self::ToolCallCompleted => "tool_call_completed",
            Self::ApprovalRequested => "approval_requested",
            Self::ApprovalResolved => "approval_resolved",
            Self::InputRequested => "input_requested",
            Self::SubagentStarted => "subagent_started",
            Self::SubagentEvent => "subagent_event",
            Self::SubagentCompleted => "subagent_completed",
            Self::UsageUpdated => "usage_updated",
            Self::ProviderWarning => "provider_warning",
            Self::ProviderFault => "provider_fault",
            Self::RunTerminal => "run_terminal",
        }
    }

    /// Parse the exact stable spelling, or nothing.
    #[must_use]
    pub fn from_spelling(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|kind| kind.as_str() == value)
    }

    /// Whether this kind ends a run.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(self, Self::RunTerminal)
    }

    /// Whether a record of this kind can only ever be [`Authority::Synthetic`].
    ///
    /// True for [`EventKind::AssistantMessageDelta`] alone. The rule is
    /// one-way: every other kind may be synthetic — a warning Automonique
    /// raises about its own budget is not something a provider said — and only
    /// this one is forbidden from being authoritative.
    #[must_use]
    pub const fn is_preview_only(self) -> bool {
        matches!(self, Self::AssistantMessageDelta)
    }

    /// Whether a step status is required, allowed or forbidden for this kind.
    ///
    /// Required exactly where a renderer would otherwise have to re-derive the
    /// state from the kind's spelling: a Slack task card and the desktop client
    /// each draw a tool call and a subagent from the status they are handed.
    #[must_use]
    pub const fn step_rule(self) -> MemberRule {
        match self {
            Self::ToolCallStarted
            | Self::ToolCallUpdated
            | Self::ToolCallCompleted
            | Self::SubagentStarted
            | Self::SubagentEvent
            | Self::SubagentCompleted => MemberRule::Required,
            Self::ProviderConnected
            | Self::ProviderDisconnected
            | Self::SessionCreated
            | Self::SessionLoaded
            | Self::SessionUpdated
            | Self::TurnQueued
            | Self::TurnStarted
            | Self::TurnSteered
            | Self::TurnInterrupted
            | Self::TurnCompleted
            | Self::AssistantMessageDelta
            | Self::AssistantMessageCompleted
            | Self::ApprovalRequested
            | Self::ApprovalResolved
            | Self::InputRequested
            | Self::UsageUpdated
            | Self::ProviderWarning
            | Self::ProviderFault
            | Self::RunTerminal => MemberRule::Forbidden,
        }
    }

    /// Whether a retry context is required, allowed or forbidden for this kind.
    ///
    /// Required on both problem kinds, because "the provider said no" and "the
    /// provider said no and will say yes in nine seconds" are different facts
    /// and a consumer that had to guess which it held would guess wrong.
    #[must_use]
    pub const fn retry_rule(self) -> MemberRule {
        match self {
            Self::ProviderWarning | Self::ProviderFault => MemberRule::Required,
            Self::ProviderConnected
            | Self::ProviderDisconnected
            | Self::SessionCreated
            | Self::SessionLoaded
            | Self::SessionUpdated
            | Self::TurnQueued
            | Self::TurnStarted
            | Self::TurnSteered
            | Self::TurnInterrupted
            | Self::TurnCompleted
            | Self::AssistantMessageDelta
            | Self::AssistantMessageCompleted
            | Self::ToolCallStarted
            | Self::ToolCallUpdated
            | Self::ToolCallCompleted
            | Self::ApprovalRequested
            | Self::ApprovalResolved
            | Self::InputRequested
            | Self::SubagentStarted
            | Self::SubagentEvent
            | Self::SubagentCompleted
            | Self::UsageUpdated
            | Self::RunTerminal => MemberRule::Forbidden,
        }
    }

    /// Whether bounded display text is required, allowed or forbidden.
    ///
    /// Required for the two assistant-message kinds, whose whole content is the
    /// text; allowed as a label where a renderer has something to name — a tool,
    /// a subagent, the sentence a fault came with, the request a paused turn is
    /// waiting on — and forbidden elsewhere, so a kind that means nothing to
    /// display cannot become a channel for provider bytes.
    ///
    /// The two pause kinds carry a label because an operator is being asked to
    /// act, and a card that says only "waiting" gives them nothing to act on.
    /// On [`EventKind::ApprovalRequested`] the label names the durable approval
    /// key first, then the tool and what it asked, so a consumer can decide the
    /// approval it was shown rather than the one it guessed. On
    /// [`EventKind::InputRequested`] the label is the provider's prompt, bounded
    /// and sanitized like every other label, and it is *absent* when the
    /// provider asked for the input to be masked: a masked request is drawn
    /// without its prompt rather than with a placeholder that could be mistaken
    /// for one.
    #[must_use]
    pub const fn text_rule(self) -> MemberRule {
        match self {
            Self::AssistantMessageDelta | Self::AssistantMessageCompleted => MemberRule::Required,
            Self::ToolCallStarted
            | Self::ToolCallUpdated
            | Self::ToolCallCompleted
            | Self::ApprovalRequested
            | Self::InputRequested
            | Self::SubagentStarted
            | Self::SubagentEvent
            | Self::SubagentCompleted
            | Self::ProviderWarning
            | Self::ProviderFault => MemberRule::Optional,
            Self::ProviderConnected
            | Self::ProviderDisconnected
            | Self::SessionCreated
            | Self::SessionLoaded
            | Self::SessionUpdated
            | Self::TurnQueued
            | Self::TurnStarted
            | Self::TurnSteered
            | Self::TurnInterrupted
            | Self::TurnCompleted
            | Self::ApprovalResolved
            | Self::UsageUpdated
            | Self::RunTerminal => MemberRule::Forbidden,
        }
    }
}

/// Whether one body member must, may, or must not accompany a kind.
///
/// Three states rather than a boolean because the middle one is real: a tool
/// call carries a label when the provider named the tool and carries none when
/// it did not, and collapsing that into "required" would force a renderer to
/// invent a name.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum MemberRule {
    /// The member must be present.
    Required,
    /// The member may be present or absent.
    Optional,
    /// The member must be absent.
    Forbidden,
}

impl MemberRule {
    /// Every rule, for coverage checks.
    pub const ALL: [Self; 3] = [Self::Required, Self::Optional, Self::Forbidden];

    /// Stable lowercase spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Required => "required",
            Self::Optional => "optional",
            Self::Forbidden => "forbidden",
        }
    }

    /// Whether a presence satisfies this rule.
    #[must_use]
    pub const fn admits(self, present: bool) -> bool {
        match self {
            Self::Required => present,
            Self::Optional => true,
            Self::Forbidden => !present,
        }
    }
}

/// How far one step of work has got.
///
/// Carried rather than derived. A consumer can reach `ToolCallUpdated` without
/// having seen `ToolCallStarted` — it subscribed late, or an earlier frame was
/// coalesced away — and a renderer that inferred the state from the kind would
/// then draw a step that never began.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum StepStatus {
    /// Admitted, not begun.
    Pending,
    /// Running now.
    InProgress,
    /// Finished, and it worked.
    Completed,
    /// Finished, and it did not.
    Error,
}

impl StepStatus {
    /// Every status, in lifecycle order.
    pub const ALL: [Self; 4] = [
        Self::Pending,
        Self::InProgress,
        Self::Completed,
        Self::Error,
    ];

    /// Stable lowercase wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::InProgress => "in_progress",
            Self::Completed => "completed",
            Self::Error => "error",
        }
    }

    /// Parse the exact stable spelling, or nothing.
    #[must_use]
    pub fn from_spelling(value: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|status| status.as_str() == value)
    }

    /// Whether the step has stopped moving.
    #[must_use]
    pub const fn is_settled(self) -> bool {
        matches!(self, Self::Completed | Self::Error)
    }
}

impl fmt::Display for StepStatus {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// What class of condition a warning or a fault reports.
///
/// Closed, and deliberately coarse: it exists so a consumer can decide whether
/// to wait, to fall back, or to stop, and a vocabulary fine enough to name
/// every provider's own error taxonomy would be a vocabulary nothing could act
/// on uniformly.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum RetryCategory {
    /// The provider asked for the request rate to come down.
    RateLimited,
    /// The provider had no capacity to spare.
    Overloaded,
    /// Nothing answered within the time allowed.
    Timeout,
    /// The connection, not the provider, failed.
    Transport,
    /// The provider considered the request itself wrong.
    Rejected,
    /// Automonique's own machinery could not proceed.
    Internal,
}

impl RetryCategory {
    /// Every category, in canonical order.
    pub const ALL: [Self; 6] = [
        Self::RateLimited,
        Self::Overloaded,
        Self::Timeout,
        Self::Transport,
        Self::Rejected,
        Self::Internal,
    ];

    /// Stable lowercase wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::RateLimited => "rate_limited",
            Self::Overloaded => "overloaded",
            Self::Timeout => "timeout",
            Self::Transport => "transport",
            Self::Rejected => "rejected",
            Self::Internal => "internal",
        }
    }

    /// Parse the exact stable spelling, or nothing.
    #[must_use]
    pub fn from_spelling(value: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|category| category.as_str() == value)
    }
}

impl fmt::Display for RetryCategory {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Longest wait a retry context may advertise.
///
/// The same five-minute ceiling the Telegram transport clamps `retry_after` to,
/// for the same reason: a delay longer than any operator will wait through is
/// indistinguishable from a refusal, and dressing one as the other costs a user
/// the five minutes before they find out.
pub const MAX_RETRY_AFTER_MS: u64 = 300_000;

/// Why a warning or a fault might be tried again, and when.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RetryContext {
    category: RetryCategory,
    retryable: bool,
    retry_after_ms: Option<u64>,
    attempt: u32,
}

impl RetryContext {
    /// Record the retry semantics of one problem.
    ///
    /// `attempt` is the ordinal of the attempt that met it, counted from one.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::RetryContextIncoherent`] for an `attempt` of zero,
    /// which names an attempt nobody made; for a `retry_after_ms` on a context
    /// that is not retryable, which would be a wait for something that will
    /// never happen; and for a wait above [`MAX_RETRY_AFTER_MS`].
    pub const fn new(
        category: RetryCategory,
        retryable: bool,
        retry_after_ms: Option<u64>,
        attempt: u32,
    ) -> Result<Self, EventError> {
        if attempt == 0 {
            return Err(EventError::RetryContextIncoherent { field: "attempt" });
        }
        match retry_after_ms {
            Some(delay) if !retryable || delay > MAX_RETRY_AFTER_MS => {
                return Err(EventError::RetryContextIncoherent {
                    field: "retry_after_ms",
                });
            }
            Some(_) | None => {}
        }
        Ok(Self {
            category,
            retryable,
            retry_after_ms,
            attempt,
        })
    }

    /// The class of condition.
    #[must_use]
    pub const fn category(self) -> RetryCategory {
        self.category
    }

    /// Whether trying again could succeed.
    #[must_use]
    pub const fn retryable(self) -> bool {
        self.retryable
    }

    /// How long to wait first, when the provider said.
    #[must_use]
    pub const fn retry_after_ms(self) -> Option<u64> {
        self.retry_after_ms
    }

    /// Which attempt met this condition, counted from one.
    #[must_use]
    pub const fn attempt(self) -> u32 {
        self.attempt
    }
}

/// Why an event, cursor or approval was refused.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EventError {
    /// A raw payload exceeded the inline ceiling and needs an artifact.
    RawPayloadTooLarge {
        /// Maximum inline bytes.
        max_bytes: usize,
        /// Supplied bytes.
        actual_bytes: usize,
    },
    /// A bounded source field was empty, oversized or contained a control.
    SourceFieldInvalid {
        /// The rejected field.
        field: &'static str,
    },
    /// A sequence did not strictly increase.
    SequenceNotIncreasing {
        /// Last accepted sequence.
        last: u64,
        /// Offered sequence.
        offered: u64,
    },
    /// A second terminal record was offered for one run.
    TerminalAlreadyRecorded {
        /// Sequence of the terminal already held.
        existing: u64,
    },
    /// An event arrived after the run reached its terminal state.
    RunAlreadyTerminal,
    /// A cursor was moved backwards.
    CursorWentBackwards {
        /// Current cursor position.
        current: u64,
        /// Offered position.
        offered: u64,
    },
    /// A second, differing decision was offered for one approval.
    ApprovalConflict {
        /// The decision already recorded.
        recorded: ApprovalDecision,
        /// The decision offered.
        offered: ApprovalDecision,
    },
    /// Preview retention would outlive authoritative retention.
    RetentionWouldOutliveEvidence {
        /// Preview horizon in milliseconds.
        preview_ms: i64,
        /// Authoritative horizon in milliseconds.
        authoritative_ms: i64,
    },
    /// A retry context described a retry that cannot be made.
    RetryContextIncoherent {
        /// The field that disagrees with the rest.
        field: &'static str,
    },
    /// A body member was absent where its kind requires one, or present where
    /// its kind forbids one.
    BodyMemberRefused {
        /// The member that broke the rule.
        member: &'static str,
        /// The kind whose rule it broke.
        kind: EventKind,
        /// What that kind requires of the member.
        rule: MemberRule,
    },
    /// A record of a preview-only kind claimed authority.
    ///
    /// [`EventKind::AssistantMessageDelta`] names text that may still change.
    /// A record of it marked [`Authority::Authoritative`] would be exactly the
    /// confusion the two types exist to prevent, arriving through the one door
    /// the type split leaves open.
    PreviewClaimedAuthority {
        /// The kind that cannot be authoritative.
        kind: EventKind,
    },
}

impl EventError {
    /// Stable machine-readable category.
    #[must_use]
    pub const fn category(&self) -> &'static str {
        match self {
            Self::RawPayloadTooLarge { .. } => "raw_payload_too_large",
            Self::SourceFieldInvalid { .. } => "source_field_invalid",
            Self::SequenceNotIncreasing { .. } => "sequence_not_increasing",
            Self::TerminalAlreadyRecorded { .. } => "terminal_already_recorded",
            Self::RunAlreadyTerminal => "run_already_terminal",
            Self::CursorWentBackwards { .. } => "cursor_went_backwards",
            Self::ApprovalConflict { .. } => "approval_conflict",
            Self::RetentionWouldOutliveEvidence { .. } => "retention_would_outlive_evidence",
            Self::RetryContextIncoherent { .. } => "retry_context_incoherent",
            Self::BodyMemberRefused { .. } => "body_member_refused",
            Self::PreviewClaimedAuthority { .. } => "preview_claimed_authority",
        }
    }
}

impl fmt::Display for EventError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RawPayloadTooLarge {
                max_bytes,
                actual_bytes,
            } => write!(
                formatter,
                "raw payload is {actual_bytes} bytes; the inline maximum is {max_bytes}"
            ),
            Self::SourceFieldInvalid { field } => {
                write!(formatter, "source field {field} is invalid")
            }
            Self::SequenceNotIncreasing { last, offered } => write!(
                formatter,
                "sequence {offered} does not increase past {last}"
            ),
            Self::TerminalAlreadyRecorded { existing } => write!(
                formatter,
                "the run already reached its terminal record at sequence {existing}"
            ),
            Self::RunAlreadyTerminal => formatter.write_str("the run is already terminal"),
            Self::CursorWentBackwards { current, offered } => write!(
                formatter,
                "cursor cannot move from {current} back to {offered}"
            ),
            Self::ApprovalConflict { recorded, offered } => write!(
                formatter,
                "approval already decided {} and cannot become {}",
                recorded.as_str(),
                offered.as_str()
            ),
            Self::RetentionWouldOutliveEvidence {
                preview_ms,
                authoritative_ms,
            } => write!(
                formatter,
                "preview retention of {preview_ms}ms would outlive authoritative \
                 retention of {authoritative_ms}ms"
            ),
            Self::RetryContextIncoherent { field } => {
                write!(formatter, "retry context field {field} is incoherent")
            }
            Self::BodyMemberRefused { member, kind, rule } => write!(
                formatter,
                "body member {member} is {} for {}",
                rule.as_str(),
                kind.as_str()
            ),
            Self::PreviewClaimedAuthority { kind } => write!(
                formatter,
                "{} is preview-only and cannot be authoritative",
                kind.as_str()
            ),
        }
    }
}

impl Error for EventError {}

/// A bounded raw provider record, or a reference to one held as an artifact.
///
/// An unbounded raw record is not representable, so provider output cannot fill
/// durable storage through this type.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RawPayload {
    /// Payload small enough to carry inline.
    Inline(Vec<u8>),
    /// Payload held as an artifact, referenced by digest.
    Artifact(String),
}

/// One bounded raw provider record.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawProviderRecord {
    provenance: BinaryProvenance,
    source_type: String,
    source_cursor: String,
    payload: RawPayload,
}

impl RawProviderRecord {
    /// Record a provider event with an inline payload.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::RawPayloadTooLarge`] above the inline ceiling — a
    /// caller must reference an artifact instead — or
    /// [`EventError::SourceFieldInvalid`] for a bad coordinate.
    pub fn inline(
        provenance: BinaryProvenance,
        source_type: &str,
        source_cursor: &str,
        payload: Vec<u8>,
    ) -> Result<Self, EventError> {
        source_field(source_type, "source_type")?;
        source_field(source_cursor, "source_cursor")?;
        if payload.len() > MAX_INLINE_RAW_BYTES {
            return Err(EventError::RawPayloadTooLarge {
                max_bytes: MAX_INLINE_RAW_BYTES,
                actual_bytes: payload.len(),
            });
        }
        Ok(Self {
            provenance,
            source_type: source_type.to_owned(),
            source_cursor: source_cursor.to_owned(),
            payload: RawPayload::Inline(payload),
        })
    }

    /// Record a provider event whose payload lives in an artifact.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::SourceFieldInvalid`] for a bad coordinate.
    pub fn artifact(
        provenance: BinaryProvenance,
        source_type: &str,
        source_cursor: &str,
        digest: &str,
    ) -> Result<Self, EventError> {
        source_field(source_type, "source_type")?;
        source_field(source_cursor, "source_cursor")?;
        source_field(digest, "artifact_digest")?;
        Ok(Self {
            provenance,
            source_type: source_type.to_owned(),
            source_cursor: source_cursor.to_owned(),
            payload: RawPayload::Artifact(digest.to_owned()),
        })
    }

    /// The binary this record came from.
    #[must_use]
    pub const fn provenance(&self) -> &BinaryProvenance {
        &self.provenance
    }

    /// The provider's own event type.
    #[must_use]
    pub fn source_type(&self) -> &str {
        &self.source_type
    }

    /// The provider's own sequence or cursor.
    #[must_use]
    pub fn source_cursor(&self) -> &str {
        &self.source_cursor
    }

    /// The bounded payload.
    #[must_use]
    pub const fn payload(&self) -> &RawPayload {
        &self.payload
    }
}

/// Where a normalized event sits in the provider's own coordinates.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EventCoordinates {
    session: ProviderSessionId,
    turn: Option<ProviderTurnId>,
    item: Option<ProviderItemId>,
}

impl EventCoordinates {
    /// Locate an event within a session, optionally a turn and item.
    #[must_use]
    pub const fn new(
        session: ProviderSessionId,
        turn: Option<ProviderTurnId>,
        item: Option<ProviderItemId>,
    ) -> Self {
        Self {
            session,
            turn,
            item,
        }
    }

    /// The owning session.
    #[must_use]
    pub const fn session(&self) -> &ProviderSessionId {
        &self.session
    }
}

/// An ephemeral assistant delta.
///
/// Preview by construction: there is no authority field to set, so a delta
/// cannot be marked authoritative and cannot be handed to terminal reporting.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PreviewEvent {
    sequence: u64,
    coordinates: EventCoordinates,
    at: EpochMillis,
    text: String,
}

impl PreviewEvent {
    /// Record an assistant preview delta.
    #[must_use]
    pub fn new(sequence: u64, coordinates: EventCoordinates, at: EpochMillis, text: &str) -> Self {
        Self {
            sequence,
            coordinates,
            at,
            text: text.to_owned(),
        }
    }

    /// Automonique sequence.
    #[must_use]
    pub const fn sequence(&self) -> u64 {
        self.sequence
    }

    /// When the delta was observed.
    #[must_use]
    pub const fn at(&self) -> EpochMillis {
        self.at
    }

    /// The ephemeral text.
    #[must_use]
    pub fn text(&self) -> &str {
        &self.text
    }
}

/// Everything one recorded event is built from.
///
/// A struct rather than eight positional arguments: the two body members were
/// added after the fact, and a caller that had silently gained two more
/// `Option`s in a row of seven would be exactly the reader who gets them the
/// wrong way round.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RecordedEventParts {
    /// Automonique sequence.
    pub sequence: u64,
    /// Where the event sits in provider coordinates.
    pub coordinates: EventCoordinates,
    /// What happened.
    pub kind: EventKind,
    /// How much the record may be relied upon.
    pub authority: Authority,
    /// When it happened.
    pub at: EpochMillis,
    /// The provider schema version it was normalized from.
    pub source_schema_version: u32,
    /// The bounded raw record, when one was retained.
    pub raw: Option<RawProviderRecord>,
    /// Step lifecycle, required by the tool-call and subagent kinds.
    pub step: Option<StepStatus>,
    /// Retry semantics, required by the two problem kinds.
    pub retry: Option<RetryContext>,
}

/// An authoritative or synthetic event, which terminal reporting may use.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RecordedEvent {
    sequence: u64,
    coordinates: EventCoordinates,
    kind: EventKind,
    authority: Authority,
    at: EpochMillis,
    source_schema_version: u32,
    raw: Option<RawProviderRecord>,
    step: Option<StepStatus>,
    retry: Option<RetryContext>,
}

impl RecordedEvent {
    /// Record an event with an explicit authority and a body its kind admits.
    ///
    /// Authority is a required field. There is no constructor that infers or
    /// defaults it.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::PreviewClaimedAuthority`] for an authoritative
    /// record of a preview-only kind, and [`EventError::BodyMemberRefused`] for
    /// a body member its kind requires and did not get, or forbids and did.
    pub fn new(parts: RecordedEventParts) -> Result<Self, EventError> {
        let RecordedEventParts {
            sequence,
            coordinates,
            kind,
            authority,
            at,
            source_schema_version,
            raw,
            step,
            retry,
        } = parts;
        if kind.is_preview_only() && matches!(authority, Authority::Authoritative) {
            return Err(EventError::PreviewClaimedAuthority { kind });
        }
        admit_member("step", kind, kind.step_rule(), step.is_some())?;
        admit_member("retry", kind, kind.retry_rule(), retry.is_some())?;
        Ok(Self {
            sequence,
            coordinates,
            kind,
            authority,
            at,
            source_schema_version,
            raw,
            step,
            retry,
        })
    }

    /// Step lifecycle, present exactly where the kind requires one.
    #[must_use]
    pub const fn step(&self) -> Option<StepStatus> {
        self.step
    }

    /// Retry semantics, present exactly where the kind requires one.
    #[must_use]
    pub const fn retry(&self) -> Option<RetryContext> {
        self.retry
    }

    /// Automonique sequence.
    #[must_use]
    pub const fn sequence(&self) -> u64 {
        self.sequence
    }

    /// Event kind.
    #[must_use]
    pub const fn kind(&self) -> EventKind {
        self.kind
    }

    /// Authority of this record.
    #[must_use]
    pub const fn authority(&self) -> Authority {
        self.authority
    }

    /// When the event occurred.
    #[must_use]
    pub const fn at(&self) -> EpochMillis {
        self.at
    }

    /// The provider schema version this was normalized from.
    #[must_use]
    pub const fn source_schema_version(&self) -> u32 {
        self.source_schema_version
    }

    /// The bounded raw record, when one was retained.
    #[must_use]
    pub const fn raw(&self) -> Option<&RawProviderRecord> {
        self.raw.as_ref()
    }

    /// Where the event sits in provider coordinates.
    #[must_use]
    pub const fn coordinates(&self) -> &EventCoordinates {
        &self.coordinates
    }
}

/// The recorded event stream of one run.
///
/// Accepts [`RecordedEvent`] only. A [`PreviewEvent`] cannot be offered, which
/// is what makes "a preview never reaches terminal reporting" a type property
/// rather than a review comment.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RunTimeline {
    events: Vec<RecordedEvent>,
    terminal: Option<u64>,
}

impl RunTimeline {
    /// Start an empty timeline.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            events: Vec::new(),
            terminal: None,
        }
    }

    /// Append one recorded event.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::SequenceNotIncreasing`] for a duplicate or
    /// out-of-order sequence, [`EventError::TerminalAlreadyRecorded`] for a
    /// second terminal, and [`EventError::RunAlreadyTerminal`] for anything
    /// after one.
    pub fn record(&mut self, event: RecordedEvent) -> Result<(), EventError> {
        if let Some(last) = self.events.last()
            && event.sequence() <= last.sequence()
        {
            return Err(EventError::SequenceNotIncreasing {
                last: last.sequence(),
                offered: event.sequence(),
            });
        }
        if let Some(existing) = self.terminal {
            return Err(if event.kind().is_terminal() {
                EventError::TerminalAlreadyRecorded { existing }
            } else {
                EventError::RunAlreadyTerminal
            });
        }
        if event.kind().is_terminal() {
            self.terminal = Some(event.sequence());
        }
        self.events.push(event);
        Ok(())
    }

    /// The recorded events, in sequence order.
    #[must_use]
    pub fn events(&self) -> &[RecordedEvent] {
        &self.events
    }

    /// The terminal outcome, when the run has reached one.
    ///
    /// Derived only from recorded events, so dropping every preview cannot
    /// change it.
    #[must_use]
    pub fn terminal(&self) -> Option<&RecordedEvent> {
        self.events.iter().find(|event| event.kind().is_terminal())
    }
}

/// What a consumer has durably observed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConsumerCursor {
    consumer: String,
    topic: String,
    position: u64,
}

impl ConsumerCursor {
    /// Record a consumer's position on a topic.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::SourceFieldInvalid`] for a bad identifier.
    pub fn new(consumer: &str, topic: &str, position: u64) -> Result<Self, EventError> {
        source_field(consumer, "consumer")?;
        source_field(topic, "topic")?;
        Ok(Self {
            consumer: consumer.to_owned(),
            topic: topic.to_owned(),
            position,
        })
    }

    /// Current position.
    #[must_use]
    pub const fn position(&self) -> u64 {
        self.position
    }

    /// Move the cursor forward.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::CursorWentBackwards`]. A cursor never rewinds
    /// silently.
    pub fn advance_to(&mut self, position: u64) -> Result<(), EventError> {
        if position < self.position {
            return Err(EventError::CursorWentBackwards {
                current: self.position,
                offered: position,
            });
        }
        self.position = position;
        Ok(())
    }
}

/// The answer to a subscription request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum SubscriptionStart {
    /// Live delivery may begin at this position.
    Live {
        /// First sequence the consumer will receive.
        from: u64,
    },
    /// The cursor is outside retention; a bounded snapshot is required first.
    ResyncRequired {
        /// Lowest sequence still retained.
        snapshot_from: u64,
        /// Highest sequence still retained.
        snapshot_to: u64,
    },
}

/// Resolve where a consumer may resume.
///
/// A cursor outside the retained range yields
/// [`SubscriptionStart::ResyncRequired`] carrying snapshot coordinates — never
/// a silent partial stream and never an empty success.
#[must_use]
pub fn resolve_subscription(
    cursor: &ConsumerCursor,
    retained_from: u64,
    retained_to: u64,
) -> SubscriptionStart {
    if cursor.position() < retained_from {
        SubscriptionStart::ResyncRequired {
            snapshot_from: retained_from,
            snapshot_to: retained_to,
        }
    } else {
        SubscriptionStart::Live {
            from: cursor.position(),
        }
    }
}

/// What class of authority a provider asked for.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ApprovalClass {
    /// Running a command.
    Command,
    /// Reading or writing a file.
    File,
    /// Reaching the network.
    Network,
    /// Calling an MCP server.
    Mcp,
    /// Asking the user for input.
    Elicitation,
    /// Any other permission the provider defines.
    Permission,
}

/// A decision on a provider approval request.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ApprovalDecision {
    /// Permit this request.
    Allow,
    /// Refuse this request.
    Deny,
}

impl ApprovalDecision {
    /// Stable lowercase wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Allow => "allow",
            Self::Deny => "deny",
        }
    }
}

/// A provider's request for authority it does not already have.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderApprovalRequest {
    class: ApprovalClass,
    request: ProviderRequestId,
    item: Option<ProviderItemId>,
    turn: ProviderTurnId,
}

impl ProviderApprovalRequest {
    /// Record an approval request with its original coordinates.
    #[must_use]
    pub const fn new(
        class: ApprovalClass,
        request: ProviderRequestId,
        item: Option<ProviderItemId>,
        turn: ProviderTurnId,
    ) -> Self {
        Self {
            class,
            request,
            item,
            turn,
        }
    }

    /// The request correlation identity.
    #[must_use]
    pub const fn request(&self) -> &ProviderRequestId {
        &self.request
    }

    /// The class of authority sought.
    #[must_use]
    pub const fn class(&self) -> ApprovalClass {
        self.class
    }
}

/// The durable record of one approval decision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApprovalReceipt {
    request: ProviderRequestId,
    decision: ApprovalDecision,
    at: EpochMillis,
}

impl ApprovalReceipt {
    /// The decision recorded.
    #[must_use]
    pub const fn decision(&self) -> ApprovalDecision {
        self.decision
    }

    /// When it was decided.
    #[must_use]
    pub const fn at(&self) -> EpochMillis {
        self.at
    }

    /// The request it answers.
    #[must_use]
    pub const fn request(&self) -> &ProviderRequestId {
        &self.request
    }
}

/// Decisions recorded against provider approval requests.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ApprovalLedger {
    receipts: Vec<ApprovalReceipt>,
}

impl ApprovalLedger {
    /// Start an empty ledger.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            receipts: Vec::new(),
        }
    }

    /// Record a decision, idempotently.
    ///
    /// Replaying the same decision for the same request returns the identical
    /// receipt, including its original timestamp.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::ApprovalConflict`] when a differing decision is
    /// offered for a request already decided. A decision is never replaced.
    pub fn decide(
        &mut self,
        request: &ProviderApprovalRequest,
        decision: ApprovalDecision,
        at: EpochMillis,
    ) -> Result<ApprovalReceipt, EventError> {
        if let Some(existing) = self
            .receipts
            .iter()
            .find(|receipt| receipt.request == *request.request())
        {
            return if existing.decision == decision {
                Ok(existing.clone())
            } else {
                Err(EventError::ApprovalConflict {
                    recorded: existing.decision,
                    offered: decision,
                })
            };
        }
        let receipt = ApprovalReceipt {
            request: request.request().clone(),
            decision,
            at,
        };
        self.receipts.push(receipt.clone());
        Ok(receipt)
    }
}

/// How long each class of record is kept.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RetentionPolicy {
    preview_ms: i64,
    authoritative_ms: i64,
}

impl RetentionPolicy {
    /// Declare separate horizons for previews and authoritative records.
    ///
    /// # Errors
    ///
    /// Returns [`EventError::RetentionWouldOutliveEvidence`] when previews
    /// would be kept at least as long as the evidence derived from them, which
    /// inverts the point of the split.
    pub const fn new(preview_ms: i64, authoritative_ms: i64) -> Result<Self, EventError> {
        if preview_ms >= authoritative_ms {
            return Err(EventError::RetentionWouldOutliveEvidence {
                preview_ms,
                authoritative_ms,
            });
        }
        Ok(Self {
            preview_ms,
            authoritative_ms,
        })
    }

    /// Preview horizon in milliseconds.
    #[must_use]
    pub const fn preview_ms(self) -> i64 {
        self.preview_ms
    }

    /// Authoritative horizon in milliseconds.
    #[must_use]
    pub const fn authoritative_ms(self) -> i64 {
        self.authoritative_ms
    }

    /// Drop previews older than the preview horizon.
    ///
    /// Takes previews only. There is no signature through which expiring a
    /// preview could reach a [`RecordedEvent`], so preview expiry cannot remove
    /// the record a report was derived from.
    pub fn expire_previews(self, previews: &mut Vec<PreviewEvent>, now: EpochMillis) {
        previews.retain(|preview| {
            now.as_millis().saturating_sub(preview.at().as_millis()) < self.preview_ms
        });
    }
}

/// Hold one body member to the rule its kind states.
///
/// Shared by [`RecordedEvent`] and by [`crate::progress_api::ProgressBody`], so
/// the in-memory record and the wire body cannot disagree about which members a
/// kind carries.
pub(crate) const fn admit_member(
    member: &'static str,
    kind: EventKind,
    rule: MemberRule,
    present: bool,
) -> Result<(), EventError> {
    if rule.admits(present) {
        Ok(())
    } else {
        Err(EventError::BodyMemberRefused { member, kind, rule })
    }
}

fn source_field(value: &str, field: &'static str) -> Result<(), EventError> {
    if value.is_empty()
        || value.len() > MAX_SOURCE_FIELD_BYTES
        || value.chars().any(char::is_control)
    {
        return Err(EventError::SourceFieldInvalid { field });
    }
    Ok(())
}
