// SPDX-License-Identifier: Elastic-2.0
import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const id='abcdefghijklmnopqrstuvwx';
// Small, valid multi-page PDF with a document outline and searchable text.
function pdf(){const objects=['<< /Type /Catalog /Pages 2 0 R /Outlines 9 0 R >>','<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 500] /Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>','','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 500] /Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>','','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Title (Viewer fixture) >>','<< /Type /Outlines /First 10 0 R /Last 10 0 R /Count 1 >>','<< /Title (Second chapter) /Parent 9 0 R /Dest [5 0 R /Fit] >>'];for(const [index,text] of [[3,'First page of Monique report'],[5,'Second page with searchable zebra']]){const stream='0.1 0.2 0.6 rg 30 300 340 140 re f\n0 0 0 rg BT /F1 18 Tf 30 460 Td ('+text+') Tj ET\n';objects[index]='<< /Length '+Buffer.byteLength(stream)+' >>\nstream\n'+stream+'endstream';}let result='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(result));result+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const start=Buffer.byteLength(result);result+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF';return Buffer.from(result);}
let contents,files,errors,requests;
test.beforeEach(async({page})=>{
 errors=[];requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 contents={'report.pdf':pdf(),'one.svg':Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="#5160dd"/><text x="30" y="90" fill="white" font-size="50">One</text></svg>'),'two.svg':Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="300"><rect width="200" height="300" fill="green"/></svg>'),'readme.md':Buffer.from('# A formatted report\n\n**Important** text and a [link](https://example.invalid/).\n\n<script>parent.postMessage({type:"stolen"},"*")</script>'),'data.csv':Buffer.from('Name,Quantity\n"Example, Inc",12\nAlpha,3\nZebra,25'),'data.json':Buffer.from('{"safe":"<script>bad()</script>","count":2}')};
 const types={'pdf':'application/pdf',svg:'image/svg+xml',md:'text/markdown',csv:'text/csv',json:'application/json'};files=Object.entries(contents).map(([path,data])=>({path,type:types[path.split('.').pop()],bytes:data.length,chunks:1}));
 const names=['dashboard.html','dashboard.css','dashboard.js','artifacts.css','artifacts.js','artifact-viewer.html','artifact-pdf.js','platform-cockpit-core.js'];const assets=Object.fromEntries(await Promise.all(names.map(async n=>[n,await readFile(new URL('../../assets/'+n,import.meta.url),'utf8')])));
 await page.route('**/*',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/')return route.fulfill({contentType:'text/html',body:assets['dashboard.html']});if(path.startsWith('/assets/')||path==='/artifact-pdf.js'){const name=path.split('/').pop();return route.fulfill({contentType:name.endsWith('.css')?'text/css':'text/javascript',body:assets[name]||''});}if(path==='/artifact-viewer')return route.fulfill({contentType:'text/html',headers:{'Content-Security-Policy':"default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src data: blob:; media-src blob:; font-src data: blob:; connect-src 'none'; form-action 'none'; base-uri 'none'; frame-ancestors 'self'; sandbox allow-scripts"},body:assets['artifact-viewer.html']});if(path==='/api/artifacts'){const b=route.request().postDataJSON(),artifact={id,title:'Asset collection',can_manage:true,visibility:'private',version_count:1,revision:1,url:'/artifacts?id='+id,created_at:'2026-01-01',updated_at:'2026-01-01',versions:[{number:1,entry:files[0].path,files,created_at:'2026-01-01'}]};if(b.action==='list')return route.fulfill({json:{items:[artifact]}});if(b.action==='get')return route.fulfill({json:{artifact}});if(b.action==='read'){const data=contents[b.path];return route.fulfill({json:{bytes:data.length,content_base64:data.toString('base64'),sha256:createHash('sha256').update(data).digest('hex')}});}}return route.fulfill({json:{}});});
});
async function open(page,path){await page.goto('https://viewer.test/#artifacts');await page.getByRole('button',{name:/Asset collection/}).click();if(path)await page.locator('.aw-file').getByRole('button',{name:new RegExp('^'+path.replaceAll('.','\\.')+'$')}).click();return page.frameLocator('.aw-preview > iframe');}
async function choose(page,path){await page.locator('.aw-file>button:first-child').filter({hasText:path}).click();return page.frameLocator('.aw-preview > iframe');}
test('PDF renders pixels and selectable text, navigates, searches, zooms and rotates',async({page})=>{
 const frame=await open(page);await expect(frame.locator('.textLayer')).toContainText('First page');await expect(frame.locator('.pdf-page > canvas')).toBeVisible();
 expect(await frame.locator('.pdf-page > canvas').evaluate(c=>{const data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return data.some((n,i)=>i%4===0&&n<200);})).toBe(true);
 await frame.getByRole('button',{name:'Page suivante',exact:true}).click();await expect(frame.locator('.textLayer')).toContainText('Second page');
 await frame.getByRole('combobox',{name:'Zoom du PDF'}).selectOption('2');await expect(frame.locator('.page-footer')).toContainText('200 %');
 await frame.getByRole('button',{name:'Pivoter le PDF'}).click();await expect.poll(()=>frame.locator('.pdf-page').evaluate(e=>e.clientWidth>e.clientHeight)).toBe(true);await expect.poll(()=>frame.locator('.textLayer span').first().evaluate(e=>{const r=e.getBoundingClientRect();return r.height>r.width;})).toBe(true);
 await frame.getByRole('searchbox',{name:'Rechercher dans le PDF'}).fill('zebra');await expect(frame.locator('.result')).toContainText('Page 2');await expect(frame.locator('.textLayer .found')).toContainText('zebra');
 await frame.getByRole('button',{name:'Pages',exact:true}).click();await expect(frame.locator('.side canvas').first()).toBeVisible();
 await frame.getByRole('button',{name:'Sommaire',exact:true}).click();await expect(frame.getByRole('button',{name:'Second chapter'})).toBeVisible();
 expect(await frame.locator('body').evaluate(()=>{try{return !!parent.document.body;}catch{return false;}})).toBe(false);
 expect(errors).toEqual([]);expect(requests.filter(u=>!u.startsWith('https://viewer.test/'))).toEqual([]);
 await page.screenshot({path:'/tmp/asset-viewer-pdf-'+test.info().project.name+'.png'});
});
test('images zoom, rotate, change backgrounds and navigate without exposing the parent',async({page})=>{
 await open(page);let frame=await choose(page,'one.svg');await expect(frame.locator('.page-footer')).toContainText('800 × 400');await frame.getByRole('combobox',{name:'Zoom de l’image'}).selectOption('2');await expect(frame.locator('.page-footer')).toContainText('200 %');await frame.getByRole('button',{name:'Pivoter'}).click();await expect(frame.locator('.image-wrap img')).toHaveCSS('transform',/matrix\(0, 1, -1, 0/);await frame.getByRole('combobox',{name:'Fond de l’image'}).selectOption('dark');await expect(frame.locator('.image-surface')).toHaveAttribute('data-background','dark');await frame.getByRole('button',{name:'Image suivante'}).click();frame=page.frameLocator('.aw-preview > iframe');await expect(frame.locator('.page-footer')).toContainText('200 × 300');await expect(page.locator('.aw-filename')).toHaveText('two.svg');expect(errors).toEqual([]);
});
test('Markdown is formatted safely and CSV and JSON can be explored',async({page})=>{
 await open(page);let frame=await choose(page,'readme.md');await expect(frame.getByRole('heading',{name:'A formatted report'})).toBeVisible();await expect(frame.locator('article strong')).toHaveText('Important');await expect(frame.locator('article script')).toHaveCount(0);await expect(frame.locator('article a')).not.toHaveAttribute('href');
 frame=await choose(page,'data.csv');await expect(frame.locator('tbody tr')).toHaveCount(3);await expect(frame.locator('tbody tr').first()).toContainText('Example, Inc');await frame.getByRole('button',{name:'Quantity',exact:true}).click();await expect(frame.locator('tbody tr').first()).toContainText('Alpha');await frame.getByRole('searchbox',{name:'Filtrer les lignes'}).fill('zebra');await expect(frame.locator('tbody tr')).toHaveCount(1);
 frame=await choose(page,'data.json');await expect(frame.locator('.code')).toContainText('"count": 2');await frame.getByRole('searchbox',{name:'Rechercher dans le texte'}).fill('safe');await expect(frame.locator('mark')).toHaveText('safe');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('invalid PDF has a recovery path and cannot break the workspace',async({page})=>{
 contents['report.pdf']=Buffer.from('This is not a PDF');files[0].bytes=contents['report.pdf'].length;
 const frame=await open(page);await expect(frame.getByRole('alert')).toContainText('télécharger');await expect(page.getByRole('button',{name:'Télécharger le fichier affiché'})).toBeVisible();
 await choose(page,'one.svg');await expect(page.frameLocator('.aw-preview > iframe').locator('.page-footer')).toContainText('800 × 400');
});
test('audio exposes playback speed and loop controls',async({page})=>{
 const data=Buffer.alloc(8044);data.write('RIFF',0);data.writeUInt32LE(8036,4);data.write('WAVEfmt ',8);data.writeUInt32LE(16,16);data.writeUInt16LE(1,20);data.writeUInt16LE(1,22);data.writeUInt32LE(8000,24);data.writeUInt32LE(8000,28);data.writeUInt16LE(1,32);data.writeUInt16LE(8,34);data.write('data',36);data.writeUInt32LE(8000,40);data.fill(128,44);contents['sample.wav']=data;files.push({path:'sample.wav',type:'audio/wav',bytes:data.length,chunks:1});
 await open(page);const frame=await choose(page,'sample.wav');await expect(frame.locator('audio')).toBeVisible();await expect(frame.locator('.page-footer')).toContainText('Audio');await frame.getByRole('combobox',{name:'Vitesse de lecture'}).selectOption('1.5');expect(await frame.locator('audio').evaluate(e=>e.playbackRate)).toBe(1.5);await frame.getByRole('button',{name:'Boucle'}).click();expect(await frame.locator('audio').evaluate(e=>e.loop)).toBe(true);await choose(page,'data.csv');await expect(page.frameLocator('.aw-preview > iframe').locator('tbody tr')).toHaveCount(3);expect(errors).toEqual([]);
});
