# SPDX-License-Identifier: Elastic-2.0

[package]
name = "automonique-lab"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex.workspace = true
nix.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
