# SPDX-License-Identifier: Elastic-2.0

[package]
name = "automonique-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
automonique-core = { path = "../automonique-core" }
automonique-observability = { path = "../automonique-observability" }
automonique-protocol = { path = "../automonique-protocol" }
automonique-store = { path = "../automonique-store" }
nix.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
