// SPDX-License-Identifier: Elastic-2.0

//! End-to-end proof over a **fixture**, never a provider.
//!
//! # Fixture provenance and safety boundary
//!
//! The "provider" here is a busybox `sh` script generated by this test file. It
//! echoes a fixed JSONL transcript to stdout and records the argv it received.
//! Its lines are hand-written to the vocabulary `src/normalize.rs` accepts at
//! HEAD, matching the shapes already pinned by `tests/codex_adapter.rs`.
//!
//! **No test in this file executes a provider CLI, contacts any network, or
//! reads any provider credential.** Everything it runs is `/usr/bin/busybox`
//! (statically linked, so one read-execute grant makes it runnable) plus the
//! script this file wrote a moment earlier.
//!
//! # Two proofs, and the difference between them
//!
//! [`a_planned_fixture_provider_runs_and_its_stdout_parses`] runs the fixture
//! **unsandboxed**, with plain [`std::process::Command`]. It proves the plan's
//! program and argv are what actually reaches a process, and that the bytes
//! such a process writes parse to the expected normalized events. It proves
//! nothing at all about confinement, and is deliberately named so.
//!
//! [`the_planned_fixture_provider_is_confined_end_to_end`] runs the same plan
//! through the runner's entry helper inside a delegated cgroup v2 domain,
//! which is where confinement is actually established. Like the runner's own
//! launch proofs it degrades loudly without such a domain, and
//! `AUTOMONIQUE_REQUIRE_ENFORCED_CONTAINMENT=1` turns that degradation into a
//! failure:
//!
//! ```sh
//! systemd-run --user --scope -p Delegate=yes \
//!   --setenv=AUTOMONIQUE_REQUIRE_ENFORCED_CONTAINMENT=1 \
//!   cargo test --manifest-path rust/Cargo.toml -p automonique-agents \
//!   --test provider_fixture
//! ```

use automonique_agents::{
    AdapterEnvironment, ExecutionMode, NormalizedEvent, ProviderDisposition, ProviderEventStream,
    ProviderExecutable, ProviderKind, ProviderLaunchPlan, ProviderNetwork, ProviderSpawnRequest,
    RunCoordinates, RunRequest, SessionScope,
};
use automonique_runner::{
    CGROUP_DIR_ENV, ContainmentDomain, ContainmentError, ContainmentLimits, RunContainment,
};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::{Read as _, Write as _};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

const BUSYBOX: &str = "/usr/bin/busybox";
const REQUIRE_ENFORCED_ENV: &str = "AUTOMONIQUE_REQUIRE_ENFORCED_CONTAINMENT";
const DRAIN_DEADLINE: Duration = Duration::from_secs(10);

/// The transcript the fixture emits, and the events it must normalize to.
fn expected_events() -> Vec<String> {
    vec![
        "1|SessionCreated|run-1|turn-1|fixture-session|".to_owned(),
        "2|TurnStarted|run-1|turn-1|fixture-session|".to_owned(),
        "3|preview|run-1|turn-1|fixture-session|partial".to_owned(),
        "4|AssistantMessageCompleted|run-1|turn-1|fixture-session|fixture answer".to_owned(),
        "5|UsageUpdated|run-1|turn-1|fixture-session|".to_owned(),
        "6|TurnCompleted|run-1|turn-1|fixture-session|".to_owned(),
    ]
}

fn summary(event: &NormalizedEvent) -> String {
    match event {
        NormalizedEvent::Preview {
            sequence,
            run_id,
            turn_id,
            provider_session_id,
            text,
        } => format!("{sequence}|preview|{run_id}|{turn_id}|{provider_session_id}|{text}"),
        NormalizedEvent::Recorded(recorded) => format!(
            "{}|{:?}|{}|{}|{}|{}",
            recorded.sequence(),
            recorded.kind(),
            recorded.run_id(),
            recorded.turn_id(),
            recorded.provider_session_id(),
            recorded.text().unwrap_or("")
        ),
    }
}

fn coordinates() -> RunCoordinates {
    RunCoordinates::new(
        "run-1",
        "turn-1",
        SessionScope::new("tenant-a", "codex-account", "codex-cli").expect("scope"),
    )
    .expect("coordinates")
}

fn run_request() -> RunRequest {
    RunRequest::new(
        coordinates(),
        ExecutionMode::NewSession,
        b"fixture prompt".as_slice(),
        AdapterEnvironment::empty(),
    )
    .expect("request")
}

struct Fixture {
    directory: tempfile::TempDir,
    plan: ProviderLaunchPlan,
    workspace: PathBuf,
}

impl Fixture {
    /// Write the fixture "provider" and plan a launch for it.
    ///
    /// The workspace path is baked into the script because a sandboxed launch
    /// `execve`s with an empty environment: there is no variable to read it
    /// from, which is the same reason a plan refuses to carry one.
    fn build() -> Self {
        let directory = tempfile::tempdir().expect("temporary directory");
        let workspace = directory.path().join("workspace");
        fs::create_dir(&workspace).expect("workspace");

        let script = format!(
            "#!{BUSYBOX} sh\n\
             # Fixture provider: fixed bytes only. Nothing here is a real CLI.\n\
             echo \"argv:$*\" > {workspace}/argv.txt\n\
             echo \"etc:$({BUSYBOX} cat /etc/hostname 2>&1)\" >> {workspace}/argv.txt\n\
             echo '{{\"type\":\"thread.started\",\"thread_id\":\"fixture-session\"}}'\n\
             echo '{{\"type\":\"turn.started\"}}'\n\
             echo '{{\"type\":\"item.started\",\"item\":{{\"id\":\"m-1\",\"type\":\"agent_message\"}}}}'\n\
             echo '{{\"type\":\"item.updated\",\"item\":{{\"id\":\"m-1\",\"type\":\"agent_message\",\"text\":\"partial\"}}}}'\n\
             echo '{{\"type\":\"item.completed\",\"item\":{{\"id\":\"m-1\",\"type\":\"agent_message\",\"text\":\"fixture answer\"}}}}'\n\
             echo '{{\"type\":\"turn.completed\",\"usage\":{{\"cached_input_tokens\":1,\"input_tokens\":2,\"output_tokens\":3}}}}'\n",
            workspace = workspace.display()
        );
        let executable = directory.path().join("fixture-provider");
        fs::write(&executable, script.as_bytes()).expect("fixture bytes");
        fs::set_permissions(&executable, fs::Permissions::from_mode(0o500)).expect("fixture mode");
        let pinned = Sha256::digest(script.as_bytes())
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();

        let plan = ProviderSpawnRequest {
            kind: ProviderKind::Codex,
            executable: ProviderExecutable::pinned(executable, pinned).expect("pinned executable"),
            // The shebang interpreter is exactly the kind of grant a plan must
            // name explicitly: without it the kernel cannot run the script,
            // and nothing widens the allowlist on the caller's behalf.
            loader_grants: vec![PathBuf::from(BUSYBOX)],
            workspace_root: workspace.clone(),
            network: ProviderNetwork::NoNetwork,
        }
        .plan(&run_request())
        .expect("plan");

        Self {
            directory,
            plan,
            workspace,
        }
    }

    fn argv_report(&self) -> String {
        fs::read_to_string(self.workspace.join("argv.txt")).expect("fixture wrote its argv")
    }

    /// Only the argv line, so a failure message never carries host details.
    fn argv_line(&self) -> String {
        self.argv_report()
            .lines()
            .next()
            .unwrap_or_default()
            .to_owned()
    }
}

/// Parse captured provider stdout with the incremental stream parser.
fn parse(stdout: &[u8]) -> Vec<String> {
    let coordinates = coordinates();
    let mode = ExecutionMode::NewSession;
    let mut stream = ProviderEventStream::new(&coordinates, &mode);
    stream.push_bytes(stdout).expect("fixture stdout accepted");
    let transcript = stream.finish().expect("complete transcript");
    assert_eq!(transcript.disposition(), ProviderDisposition::Succeeded);
    assert_eq!(
        transcript.binding().provider_session_id(),
        "fixture-session"
    );
    transcript.events().iter().map(summary).collect()
}

#[test]
fn a_planned_fixture_provider_runs_and_its_stdout_parses() {
    let fixture = Fixture::build();

    // NOT a sandboxed launch: this is a plain fork/exec, and it establishes
    // nothing about confinement. What it does establish is that the program
    // and argv a plan carries are the ones a process actually receives, and
    // that such a process's stdout parses to exact normalized events.
    let output = Command::new(fixture.plan.program())
        .args(fixture.plan.arguments())
        // The prompt is not delivered; see PromptDelivery::UnresolvedProviderStdin.
        .stdin(Stdio::null())
        .output()
        .expect("fixture runs");
    assert!(output.status.success(), "fixture exited non-zero");

    assert_eq!(parse(&output.stdout), expected_events());
    assert_eq!(
        fixture.argv_line(),
        "argv:exec --json -",
        "the plan's argv must be what the process received"
    );
    drop(fixture.directory);
}

/// The delegated domain and the runner's entry helper, or a loud degradation.
fn enforcement(proof: &str) -> Option<(ContainmentDomain, PathBuf)> {
    let helper = std::env::current_exe()
        .ok()
        .and_then(|exe| Some(exe.parent()?.parent()?.join("automonique-launch-enter")))
        .filter(|path| path.is_file());
    let domain = match ContainmentDomain::discover() {
        Ok(found) => Some(found),
        Err(error) => {
            eprintln!("[provider-fixture] NOT PROVEN {proof}: {error}");
            assert!(
                matches!(
                    error,
                    ContainmentError::DomainNotDelegated
                        | ContainmentError::NotUnifiedCgroupV2
                        | ContainmentError::MissingAtomicKill
                ),
                "undelegated environments must refuse with a typed reason, got {error:?}"
            );
            None
        }
    };
    match (domain, helper) {
        (Some(domain), Some(helper)) => {
            eprintln!(
                "[provider-fixture] ENFORCED  {proof}: domain {}",
                domain.root().display()
            );
            Some((domain, helper))
        }
        (domain, helper) => {
            if helper.is_none() {
                eprintln!(
                    "[provider-fixture] NOT PROVEN {proof}: the runner's \
                     automonique-launch-enter binary is not built in this target \
                     directory; build it with `cargo build -p automonique-runner`"
                );
            }
            assert!(
                std::env::var_os(REQUIRE_ENFORCED_ENV).is_none(),
                "{REQUIRE_ENFORCED_ENV} is set, so {proof} must run against a \
                 delegated cgroup v2 domain with the runner's entry helper built, \
                 but domain_present={} helper_present={}",
                domain.is_some(),
                helper.is_some()
            );
            None
        }
    }
}

#[test]
fn the_planned_fixture_provider_is_confined_end_to_end() {
    let Some((domain, helper)) = enforcement("the_planned_fixture_provider_is_confined_end_to_end")
    else {
        return;
    };
    let fixture = Fixture::build();
    let run_id = format!("a{}-fixture", std::process::id());
    let containment =
        RunContainment::create(&domain, &run_id, ContainmentLimits::none()).expect("containment");

    let frame = fixture.plan.encode_frame().expect("frame");
    let mut child = Command::new(&helper)
        .env_clear()
        .env(CGROUP_DIR_ENV, containment.path())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("helper spawns");
    child
        .stdin
        .take()
        .expect("stdin piped")
        .write_all(&frame)
        .expect("frame written");

    let deadline = Instant::now() + Duration::from_secs(20);
    let status = loop {
        match child.try_wait().expect("wait") {
            Some(status) => break status,
            None if Instant::now() < deadline => std::thread::sleep(Duration::from_millis(5)),
            None => {
                let _ = child.kill();
                let _ = child.wait();
                panic!("sandboxed fixture did not exit within the deadline");
            }
        }
    };
    let mut stdout = Vec::new();
    let mut stderr = String::new();
    child
        .stdout
        .take()
        .expect("stdout piped")
        .read_to_end(&mut stdout)
        .expect("stdout read");
    child
        .stderr
        .take()
        .expect("stderr piped")
        .read_to_string(&mut stderr)
        .expect("stderr read");
    assert_eq!(
        status.code(),
        Some(0),
        "the sandboxed fixture must run to completion; stderr={stderr:?}"
    );

    // The provider's own bytes, from inside the sandbox, parse exactly.
    assert_eq!(parse(&stdout), expected_events());

    let report = fixture.argv_report();
    assert_eq!(
        fixture.argv_line(),
        "argv:exec --json -",
        "argv must survive the frame round trip"
    );
    // The allowlist is real: the workspace grant let this report be written at
    // all, and /etc — which the plan does not name — is denied. The probe
    // names the file it could not open, so this cannot pass vacuously through
    // a busybox that failed to exec: that would be a different message, and
    // the transcript above already proves busybox ran.
    let etc = report
        .lines()
        .find_map(|line| line.strip_prefix("etc:"))
        .expect("the fixture probes /etc");
    assert!(
        etc.contains("/etc/hostname") && etc.contains("Permission denied"),
        "reading /etc must be denied by the plan's allowlist, saw {etc:?}"
    );

    let cgroup = containment.path().to_owned();
    containment.dispose(DRAIN_DEADLINE).expect("dispose");
    assert!(
        !Path::new(&cgroup).exists(),
        "disposal removes the run cgroup, killing the launched tree"
    );
    drop(fixture.directory);
}
