// SPDX-License-Identifier: Elastic-2.0

//! Canonical names and legacy aliases, generated from the one registry.
//!
//! GENERATED by `automonique_protocol::compat::emit_registry_module` from
//! `automonique_protocol::compat::automonique_registry`. Do not edit by hand:
//! regenerate with `AUTOMONIQUE_REGENERATE_COMPAT=1 cargo test -p
//! automonique-protocol --test compat` and commit the result.
//!
//! Every spelling here is generated from one registry entry, and a spelling
//! the registry does not declare has no constant — naming one does not
//! compile, which is what stops a hand-written alias from becoming permanent
//! by accident.

use super::IdentifierClass;

/// One canonical name declared by the registry.
///
/// The index is private, so the only values that exist are the
/// constants below, one per registry entry.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CanonicalName(usize);

impl CanonicalName {
    /// The canonical name spelled `AUTOMONIQUE_RUNNER`.
    pub const AUTOMONIQUE_RUNNER: Self = Self(0);
    /// The canonical name spelled `automonique doctor`.
    pub const AUTOMONIQUE_DOCTOR: Self = Self(1);
    /// The canonical name spelled `automonique audit`.
    pub const AUTOMONIQUE_AUDIT: Self = Self(2);
    /// The canonical name spelled `automonique-shell`.
    pub const AUTOMONIQUE_SHELL: Self = Self(3);

    /// Every canonical name, in registry order.
    pub const ALL: [Self; 4] = [
        Self::AUTOMONIQUE_RUNNER,
        Self::AUTOMONIQUE_DOCTOR,
        Self::AUTOMONIQUE_AUDIT,
        Self::AUTOMONIQUE_SHELL,
    ];

    /// The canonical spelling.
    #[must_use]
    pub const fn spelling(self) -> &'static str {
        match self.0 {
            0 => "AUTOMONIQUE_RUNNER",
            1 => "automonique doctor",
            2 => "automonique audit",
            _ => "automonique-shell",
        }
    }

    /// The identifier class this name belongs to.
    #[must_use]
    pub const fn class(self) -> IdentifierClass {
        match self.0 {
            0 => IdentifierClass::EnvironmentVariable,
            1 => IdentifierClass::Command,
            2 => IdentifierClass::Command,
            _ => IdentifierClass::Command,
        }
    }

    /// The single runtime owner every spelling of this name resolves to.
    #[must_use]
    pub const fn owner(self) -> &'static str {
        match self.0 {
            0 => "automonique-runner",
            1 => "automonique-cli",
            2 => "automonique-core",
            _ => "automonique-shell",
        }
    }

    /// The durable identity, which no rename of the canonical spelling moves.
    #[must_use]
    pub const fn durable_identity(self) -> &'static str {
        match self.0 {
            0 => "durable:runner-selection",
            1 => "durable:doctor-report",
            2 => "durable:reconciliation-audit",
            _ => "durable:shell-subsystem",
        }
    }
}

/// One legacy alias declared by the registry.
///
/// The index is private, so the only values that exist are the
/// constants below, one per registry entry.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct LegacyName(usize);

impl LegacyName {
    /// The legacy alias spelled `LEGACY_RUNNER`.
    pub const LEGACY_RUNNER: Self = Self(0);
    /// The legacy alias spelled `legacyctl`.
    pub const LEGACYCTL: Self = Self(1);
    /// The legacy alias spelled `legacy:audit`.
    pub const LEGACY_AUDIT: Self = Self(2);
    /// The legacy alias spelled `legacy-shell`.
    pub const LEGACY_SHELL: Self = Self(3);

    /// Every legacy alias, in registry order.
    pub const ALL: [Self; 4] = [
        Self::LEGACY_RUNNER,
        Self::LEGACYCTL,
        Self::LEGACY_AUDIT,
        Self::LEGACY_SHELL,
    ];

    /// The legacy spelling.
    #[must_use]
    pub const fn spelling(self) -> &'static str {
        match self.0 {
            0 => "LEGACY_RUNNER",
            1 => "legacyctl",
            2 => "legacy:audit",
            _ => "legacy-shell",
        }
    }

    /// The canonical name this alias forwards to.
    #[must_use]
    pub const fn canonical(self) -> CanonicalName {
        match self.0 {
            0 => CanonicalName::AUTOMONIQUE_RUNNER,
            1 => CanonicalName::AUTOMONIQUE_DOCTOR,
            2 => CanonicalName::AUTOMONIQUE_AUDIT,
            _ => CanonicalName::AUTOMONIQUE_SHELL,
        }
    }

    /// The migration contract that authorized this alias.
    #[must_use]
    pub const fn authorized_by(self) -> &'static str {
        match self.0 {
            0 => "docs/product-plan/reference/migration-plan.md",
            1 => "docs/product-plan/reference/migration-plan.md",
            2 => "docs/product-plan/reference/migration-plan.md",
            _ => "docs/product-plan/reference/migration-plan.md",
        }
    }

    /// The declared compatibility window.
    #[must_use]
    pub const fn retire_after(self) -> &'static str {
        match self.0 {
            0 => "0.9.0",
            1 => "0.9.0",
            2 => "0.9.0",
            _ => "0.9.0",
        }
    }
}
