// SPDX-License-Identifier: Elastic-2.0
// Reproducible, offline-at-runtime viewer. Run npm ci, then npm run build here.
import {build} from 'esbuild';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const here=path.dirname(fileURLToPath(import.meta.url));
const target=path.resolve(here,'../../rust/crates/automonique-web-entry/assets');
const pkg=path.join(here,'node_modules/pdfjs-dist');
const compile=async(entry,globalName)=> (await build({entryPoints:[entry],bundle:true,format:'iife',globalName,minify:true,write:false,target:'es2022',legalComments:'inline'})).outputFiles[0].text;
const worker=await compile(path.join(pkg,'build/pdf.worker.mjs'),'ArtifactPDFWorker');
const library=await compile(path.join(pkg,'build/pdf.mjs'),'ArtifactPDFLibrary');
const assets={};
for(const [kind,dir] of [['cMapUrl','cmaps'],['standardFontDataUrl','standard_fonts'],['wasmUrl','wasm']]){
 for(const name of await readdir(path.join(pkg,dir))){
  if(!/\.(bcmap|pfb|ttf|wasm)$/.test(name)||name.startsWith('quickjs'))continue;
  assets[kind+'/'+name]=(await readFile(path.join(pkg,dir,name))).toString('base64');
 }
}
await writeFile(path.join(target,'artifact-pdf.js'),`/* PDF.js 6.4.299, Apache-2.0; see artifact-viewer-LICENSE.txt. Generated by tools/artifact-viewer/build.mjs. */\n${library}\nglobalThis.ArtifactPDF={lib:ArtifactPDFLibrary,worker:${JSON.stringify(worker)},assets:${JSON.stringify(assets)}};\n`);
const script=await compile(path.join(here,'viewer.js'),'ArtifactViewer');
const upstreamCss=await readFile(path.join(pkg,'web/pdf_viewer.css'),'utf8');
const textLayerCss=upstreamCss.slice(upstreamCss.indexOf('.textLayer {'),upstreamCss.indexOf('.annotationLayer {'));
const css=await readFile(path.join(here,'viewer.css'),'utf8');
await writeFile(path.join(target,'artifact-viewer.html'),`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src blob: data:; media-src blob:; font-src blob: data:; connect-src 'none'; form-action 'none'; base-uri 'none'"><style>${textLayerCss}\n${css}</style></head><body><main id="viewer"><p class="status" role="status">Chargement de l’aperçu…</p></main><script>${script.replaceAll('</script','<\\/script')}</script></body></html>`);
let licenses='Third-party notices for generated artifact viewers\n\nPDF.js 6.4.299\n'+await readFile(path.join(pkg,'LICENSE'),'utf8');
licenses+='\n\nMarked 17.0.6\n'+await readFile(path.join(here,'node_modules/marked/LICENSE.md'),'utf8');
for(const dir of ['standard_fonts','wasm'])for(const name of await readdir(path.join(pkg,dir)))if(name.startsWith('LICENSE'))licenses+='\n\n'+dir+'/'+name+'\n'+await readFile(path.join(pkg,dir,name),'utf8');
await writeFile(path.join(target,'artifact-viewer-LICENSE.txt'),licenses);
console.log('Built isolated document viewer and locally bundled PDF.js engine.');
