// SPDX-License-Identifier: Elastic-2.0
import {marked} from 'marked';
const root=document.getElementById('viewer');
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(label,fn)=>{const b=node('button',label);b.type='button';b.addEventListener('click',()=>Promise.resolve().then(fn).catch(showError));return b;};
function select(label,values,value,fn){const s=node('select');s.setAttribute('aria-label',label);for(const [v,t] of values){const o=node('option',t);o.value=v;s.append(o);}s.value=value;s.addEventListener('change',()=>Promise.resolve(fn(s.value)).catch(showError));return s;}
function showError(){root.querySelector('.viewer-error')?.remove();const e=node('p','L’aperçu n’a pas pu être chargé. Vous pouvez toujours télécharger le fichier.','status error viewer-error');e.setAttribute('role','alert');root.append(e);}
let payload,active=false,objectUrls=[];
function url(blob){const value=URL.createObjectURL(blob);objectUrls.push(value);return value;}
function theme(colors){for(const [key,value] of Object.entries(colors||{}))if(['bg','ink','muted','line','soft','accent'].includes(key)&&CSS.supports('color',value))document.documentElement.style.setProperty('--'+key,value);}
function layout(){const bar=node('div',undefined,'toolbar'),body=node('div',undefined,'body'),view=node('div',undefined,'viewport'),footer=node('div',undefined,'page-footer');view.tabIndex=0;body.append(view);root.replaceChildren(bar,body,footer);return {bar,body,view,footer};}
function meta(footer,text){footer.replaceChildren(node('span',text),node('span',payload.name));}
function input(label,type='search'){const e=node('input');e.type=type;e.setAttribute('aria-label',label);return e;}
const spacer=()=>node('span',undefined,'spacer');
async function pdf(){
 const script=node('script');script.textContent=payload.pdfEngine;document.head.append(script);script.remove();
 const {lib,worker:workerCode,assets}=globalThis.ArtifactPDF;if(!lib)throw Error('PDF unavailable');
 const worker=new Worker(url(new Blob([workerCode],{type:'text/javascript'})));lib.GlobalWorkerOptions.workerPort=worker;
 addEventListener('pagehide',()=>worker.terminate(),{once:true});
 class LocalBinaryData {async fetch({kind,filename}){const encoded=assets[kind+'/'+filename];if(!encoded)throw Error('Unsupported resource');return Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));}}
 const {bar,body,view,footer}=layout();let documentPdf,pageNumber=1,rotation=0,zoom=innerWidth<600?'width':'page',renderId=0,renderTask,textLayer,searchId=0,searchTerm='',resultPages=[],resultIndex=-1,sideMode='pages',thumbObserver,thumbnailBusy=false;const thumbQueue=[],texts=new Map();
 const side=node('aside',undefined,'side');side.hidden=true;side.setAttribute('aria-label','Navigation du PDF');body.prepend(side);
 const previous=button('‹',()=>go(pageNumber-1));previous.setAttribute('aria-label','Page précédente');const next=button('›',()=>go(pageNumber+1));next.setAttribute('aria-label','Page suivante');
 const number=input('Numéro de page','number');number.min=1;number.value=1;number.addEventListener('change',()=>go(Number(number.value)));const pageCount=node('small','/ …');
 const pageLabel=node('label','Page');pageLabel.append(number,pageCount);
 const pages=button('Pages',()=>toggleSide('pages'));const outline=button('Sommaire',()=>toggleSide('outline'));
 const scale=select('Zoom du PDF',[['width','Largeur'],['page','Page entière'],['0.5','50 %'],['0.75','75 %'],['1','100 %'],['1.5','150 %'],['2','200 %'],['3','300 %'],['4','400 %']],zoom,value=>{zoom=value;render();});
 bar.append(pages,previous,pageLabel,next,scale,button('↻',()=>{rotation=(rotation+90)%360;render();}),outline);
 bar.querySelector('button:last-of-type')?.setAttribute('aria-label','Sommaire');
 [...bar.querySelectorAll('button')].find(b=>b.textContent==='↻')?.setAttribute('aria-label','Pivoter le PDF');
 const find=input('Rechercher dans le PDF');find.placeholder='Rechercher dans le PDF…';const searchStatus=node('small');searchStatus.setAttribute('role','status');let searchTimer;
 find.addEventListener('input',()=>{clearTimeout(searchTimer);searchId++;searchTimer=setTimeout(()=>search(find.value),250);});
 const prevMatch=button('↑',()=>match(-1)),nextMatch=button('↓',()=>match(1));prevMatch.setAttribute('aria-label','Résultat précédent');nextMatch.setAttribute('aria-label','Résultat suivant');prevMatch.disabled=nextMatch.disabled=true;
 const findbar=node('div',undefined,'toolbar');findbar.append(find,prevMatch,nextMatch,searchStatus);root.insertBefore(findbar,body);
 const task=lib.getDocument({data:new Uint8Array(payload.buffer),useWorkerFetch:false,BinaryDataFactory:LocalBinaryData,useWasm:true,enableXfa:false,isEvalSupported:false,maxImageSize:32000000,canvasMaxAreaInBytes:64000000,verbosity:0});
 task.onPassword=(update,reason)=>{const form=node('form',undefined,'password'),label=node('label',reason===2?'Mot de passe incorrect. Réessayez.':'Ce PDF est protégé par un mot de passe.'),pw=input('Mot de passe du PDF','password');pw.autocomplete='off';const submit=node('button','Ouvrir le PDF');submit.type='submit';label.append(pw);form.append(label,submit);view.replaceChildren(form);form.addEventListener('submit',e=>{e.preventDefault();const value=pw.value;pw.value='';view.replaceChildren(node('p','Ouverture du PDF…','status'));update(value);});pw.focus();};
 try{documentPdf=await task.promise;}catch(e){worker.terminate();throw e;}
 number.max=documentPdf.numPages;pageCount.textContent='/ '+documentPdf.numPages;
 const outlineItems=await documentPdf.getOutline();outline.disabled=!outlineItems?.length;
 function go(n){if(!documentPdf)return;const valid=Number.isFinite(n)?Math.trunc(n):pageNumber;pageNumber=Math.max(1,Math.min(documentPdf.numPages,valid));number.value=pageNumber;view.scrollTop=0;render();}
 function highlight(){const terms=searchTerm.toLocaleLowerCase().split(/\s+/).filter(Boolean);view.querySelectorAll('.textLayer span').forEach(s=>s.classList.toggle('found',terms.length>0&&terms.some(t=>s.textContent.toLocaleLowerCase().includes(t))));}
 async function render(){
  if(!documentPdf)return;const id=++renderId;renderTask?.cancel();textLayer?.cancel();previous.disabled=pageNumber<=1;next.disabled=pageNumber>=documentPdf.numPages;number.value=pageNumber;
  try{const page=await documentPdf.getPage(pageNumber);if(id!==renderId)return;const base=page.getViewport({scale:1,rotation:(page.rotate+rotation)%360});const width=Math.max(160,view.clientWidth-40),height=Math.max(160,view.clientHeight-40);const factor=zoom==='width'?width/base.width:zoom==='page'?Math.min(width/base.width,height/base.height):Number(zoom);
   const viewport=page.getViewport({scale:Math.min(4,Math.max(.1,factor)),rotation:(page.rotate+rotation)%360});const density=Math.min(devicePixelRatio||1,2,Math.sqrt(16000000/(viewport.width*viewport.height)));
   const sheet=node('div',undefined,'pdf-page');sheet.style.width=viewport.width+'px';sheet.style.height=viewport.height+'px';sheet.style.setProperty('--total-scale-factor',viewport.scale);sheet.style.setProperty('--scale-factor',viewport.scale);const canvas=node('canvas');canvas.setAttribute('aria-label','Page '+pageNumber+' du PDF');canvas.width=Math.ceil(viewport.width*density);canvas.height=Math.ceil(viewport.height*density);const layer=node('div',undefined,'textLayer');sheet.append(canvas,layer);view.replaceChildren(sheet);
   renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:density===1?null:[density,0,0,density,0,0]});await renderTask.promise;if(id!==renderId)return;
   const text=await page.getTextContent();if(id!==renderId)return;textLayer=new lib.TextLayer({textContentSource:text,container:layer,viewport});await textLayer.render();if(id!==renderId)return;highlight();meta(footer,'Page '+pageNumber+' / '+documentPdf.numPages+' · '+Math.round(viewport.scale*100)+' %');side.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.page)===pageNumber)));
  }catch(e){if(id===renderId&&e.name!=='RenderingCancelledException'&&e.name!=='AbortException')showError();}
 }
 function toggleSide(mode){side.hidden=!side.hidden&&sideMode===mode;sideMode=mode;pages.setAttribute('aria-pressed',String(!side.hidden&&mode==='pages'));outline.setAttribute('aria-pressed',String(!side.hidden&&mode==='outline'));if(!side.hidden){if(mode==='pages')thumbnails();else if(mode==='outline')bookmarks();}if(zoom==='width'||zoom==='page')render();}
 function thumbnails(){thumbObserver?.disconnect();side.replaceChildren();thumbQueue.length=0;let loaded=0;
  thumbObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting&&!entry.target.dataset.loaded){entry.target.dataset.loaded='true';thumbQueue.push(entry.target);}drawThumb();},{root:side,rootMargin:'100px'});
  function more(){side.querySelector('.more-pages')?.remove();const end=Math.min(documentPdf.numPages,loaded+50);for(;loaded<end;loaded++){const n=loaded+1,b=button('Page '+n,()=>go(n));b.dataset.page=n;b.setAttribute('aria-current',String(n===pageNumber));side.append(b);thumbObserver.observe(b);}if(loaded<documentPdf.numPages){const b=button('Afficher plus',more);b.className='more-pages';side.append(b);}}
  more();
 }
 async function drawThumb(){if(thumbnailBusy)return;thumbnailBusy=true;try{while(thumbQueue.length){const b=thumbQueue.shift();if(!b.isConnected)continue;const page=await documentPdf.getPage(Number(b.dataset.page)),base=page.getViewport({scale:1}),viewport=page.getViewport({scale:100/base.width}),canvas=node('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.setAttribute('aria-hidden','true');await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;if(b.isConnected)b.prepend(canvas);}}catch{}finally{thumbnailBusy=false;}}
 function bookmarks(){thumbObserver?.disconnect();side.replaceChildren();let count=0;function add(items,depth){for(const item of items){if(++count>500)return;const b=button(item.title||'Sans titre',async()=>{let dest=item.dest;if(typeof dest==='string')dest=await documentPdf.getDestination(dest);if(Array.isArray(dest)){const first=dest[0],index=typeof first==='number'?first:await documentPdf.getPageIndex(first);go(index+1);}});b.className='outline-entry';b.style.paddingLeft=8+Math.min(depth,5)*10+'px';b.disabled=!item.dest;side.append(b);if(item.items)add(item.items,depth+1);}}add(outlineItems||[],0);}
 async function search(term){searchTerm=term.trim();const id=++searchId;resultPages=[];resultIndex=-1;prevMatch.disabled=nextMatch.disabled=true;highlight();if(!searchTerm){searchStatus.textContent='';if(sideMode==='search'){side.hidden=true;render();}return;}sideMode='search';side.hidden=false;thumbObserver?.disconnect();side.replaceChildren();pages.setAttribute('aria-pressed','false');outline.setAttribute('aria-pressed','false');const q=searchTerm.toLocaleLowerCase();
  try{for(let n=1;n<=documentPdf.numPages;n++){if(id!==searchId)return;searchStatus.textContent='Recherche · '+n+' / '+documentPdf.numPages;let text=texts.get(n);if(text===undefined){const page=await documentPdf.getPage(n),content=await page.getTextContent();text=content.items.map(i=>i.str||'').join(' ').slice(0,200000);if(texts.size<500)texts.set(n,text);}if(id!==searchId)return;const at=text.toLocaleLowerCase().indexOf(q);if(at>=0){resultPages.push(n);if(resultPages.length<=100){const b=button('',()=>go(n));b.className='result';b.append(node('strong','Page '+n),node('small',text.slice(Math.max(0,at-35),at+q.length+75)));side.append(b);}}}
   if(id!==searchId)return;searchStatus.textContent=resultPages.length+' page'+(resultPages.length>1?'s':'')+' trouvée'+(resultPages.length>1?'s':'');if(!resultPages.length)side.append(node('p','Aucun résultat. Les pages numérisées sans texte nécessitent une reconnaissance OCR.','status'));if(resultPages.length>100)side.append(node('p','100 résultats affichés. Les flèches parcourent tous les résultats.','status'));prevMatch.disabled=nextMatch.disabled=!resultPages.length;if(resultPages.length)match(1);else render();
  }catch{if(id===searchId)searchStatus.textContent='Recherche indisponible';}
 }
 function match(step){if(!resultPages.length)return;resultIndex=(resultIndex+step+resultPages.length)%resultPages.length;go(resultPages[resultIndex]);}
 let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);if(zoom==='width'||zoom==='page')resizeTimer=setTimeout(render,100);}).observe(view);
 view.addEventListener('keydown',e=>{if(e.key==='PageDown'||e.key==='ArrowRight'){e.preventDefault();go(pageNumber+1);}if(e.key==='PageUp'||e.key==='ArrowLeft'){e.preventDefault();go(pageNumber-1);}});
 await render();
}
function imageViewer(){
 const {bar,view,footer}=layout();view.classList.add('image-viewport');const surface=node('div',undefined,'image-surface'),wrap=node('div',undefined,'image-wrap'),img=node('img');img.alt=payload.name;img.draggable=false;wrap.append(img);surface.append(wrap);view.append(surface);let scale='fit',rotation=0,currentFactor=1;
 const zoom=select('Zoom de l’image',[['fit','Ajuster'],['0.25','25 %'],['0.5','50 %'],['1','100 %'],['2','200 %'],['4','400 %']],scale,value=>{scale=value;draw();});
 function syncZoom(){zoom.querySelector('[data-custom]')?.remove();if(![...zoom.options].some(o=>o.value===scale)){const option=node('option',Math.round(Number(scale)*100)+' %');option.value=scale;option.dataset.custom='true';zoom.append(option);}zoom.value=scale;}
 function step(mult){scale=String(Math.max(.05,Math.min(8,currentFactor*mult)));syncZoom();draw();}
 const minus=button('−',()=>step(1/1.25)),plus=button('+',()=>step(1.25));minus.setAttribute('aria-label','Réduire l’image');plus.setAttribute('aria-label','Agrandir l’image');
 bar.append(minus,zoom,plus,button('↻ Pivoter',()=>{rotation=(rotation+90)%360;draw();}),select('Fond de l’image',[['checker','Damier'],['white','Blanc'],['dark','Sombre']],'checker',value=>surface.dataset.background=value),spacer());
 const siblings=payload.images||[],index=siblings.indexOf(payload.name);const prev=button('‹',()=>parent.postMessage({type:'artifact-viewer-select',path:siblings[index-1]},'*')),next=button('›',()=>parent.postMessage({type:'artifact-viewer-select',path:siblings[index+1]},'*'));prev.setAttribute('aria-label','Image précédente');next.setAttribute('aria-label','Image suivante');prev.disabled=index<=0;next.disabled=index<0||index>=siblings.length-1;if(siblings.length>1)bar.append(prev,node('small',(index+1)+' / '+siblings.length),next);
 function draw(){if(!img.naturalWidth)return;const turned=rotation%180!==0,w=turned?img.naturalHeight:img.naturalWidth,h=turned?img.naturalWidth:img.naturalHeight;currentFactor=scale==='fit'?Math.min(1,(view.clientWidth-40)/w,(view.clientHeight-40)/h):Number(scale);currentFactor=Math.max(.01,currentFactor);wrap.style.width=w*currentFactor+'px';wrap.style.height=h*currentFactor+'px';img.style.width=img.naturalWidth*currentFactor+'px';img.style.height=img.naturalHeight*currentFactor+'px';img.style.transform='translate(-50%,-50%) rotate('+rotation+'deg)';meta(footer,img.naturalWidth+' × '+img.naturalHeight+' px · '+Math.round(currentFactor*100)+' %');}
 img.addEventListener('load',draw);img.addEventListener('error',showError);img.src=url(new Blob([payload.buffer],{type:payload.mime}));new ResizeObserver(()=>{if(scale==='fit')draw();}).observe(view);
 let drag;view.addEventListener('pointerdown',e=>{if(e.button!==0||e.pointerType==='touch')return;drag={x:e.clientX,y:e.clientY,left:view.scrollLeft,top:view.scrollTop};view.setPointerCapture(e.pointerId);view.classList.add('dragging');});view.addEventListener('pointermove',e=>{if(drag){view.scrollLeft=drag.left+drag.x-e.clientX;view.scrollTop=drag.top+drag.y-e.clientY;}});const end=()=>{drag=null;view.classList.remove('dragging');};view.addEventListener('pointerup',end);view.addEventListener('pointercancel',end);view.addEventListener('dblclick',()=>{scale=scale==='fit'?'1':'fit';syncZoom();draw();});view.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();step(e.deltaY<0?1.1:1/1.1);}},{passive:false});view.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();step(1.25);}if(e.key==='-'){e.preventDefault();step(1/1.25);}});
}
function parseCsv(text){const first=text.split(/\r?\n/,1)[0],separator=['\t',';',','].sort((a,b)=>first.split(b).length-first.split(a).length)[0];let row=[],cell='',quote=false,rows=[];for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===separator&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';if(rows.length>=10001)break;}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
function csv(text){const {bar,view,footer}=layout(),rows=parseCsv(text),headers=rows.shift()||[],search=input('Filtrer les lignes');search.placeholder='Filtrer les lignes…';let sortColumn=-1,direction=1,limit=100;const table=node('table',undefined,'data-table');bar.append(search);view.append(table);
 function draw(){table.replaceChildren();let found=rows.filter(r=>r.join(' ').toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));if(sortColumn>=0)found.sort((a,b)=>String(a[sortColumn]||'').localeCompare(String(b[sortColumn]||''),'fr',{numeric:true})*direction);const head=node('thead'),tr=node('tr');headers.slice(0,100).forEach((text,i)=>{const th=node('th');const b=button((text||'Colonne '+(i+1))+(sortColumn===i?(direction===1?' ↑':' ↓'):''),()=>{direction=sortColumn===i?-direction:1;sortColumn=i;draw();});th.setAttribute('aria-sort',sortColumn===i?(direction===1?'ascending':'descending'):'none');th.append(b);tr.append(th);});head.append(tr);const tbody=node('tbody');for(const row of found.slice(0,limit)){const tr=node('tr');row.slice(0,100).forEach(value=>tr.append(node('td',value)));tbody.append(tr);}table.append(head,tbody);bar.querySelector('.more-rows')?.remove();if(found.length>limit){const b=button('Afficher 100 lignes de plus',()=>{limit+=100;draw();});b.className='more-rows';bar.append(b);}meta(footer,Math.min(limit,found.length)+' / '+found.length+' lignes · '+headers.length+' colonnes'+(rows.length>=10000?' · aperçu limité à 10 000 lignes':''));}
 search.addEventListener('input',()=>{limit=100;draw();});draw();}
function safeMarkdown(text){const doc=new DOMParser().parseFromString(marked.parse(text,{gfm:true,breaks:false}),'text/html'),allowed=new Set(['P','BR','HR','H1','H2','H3','H4','H5','H6','UL','OL','LI','PRE','CODE','BLOCKQUOTE','STRONG','EM','DEL','TABLE','THEAD','TBODY','TR','TH','TD','A','INPUT']);for(const e of [...doc.body.querySelectorAll('*')]){if(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED'].includes(e.tagName)){e.remove();continue;}if(!allowed.has(e.tagName)){e.replaceWith(document.createTextNode(e.tagName==='IMG'?e.getAttribute('alt')||'':e.textContent));continue;}const href=e.tagName==='A'?e.getAttribute('href'):null,checked=e.tagName==='INPUT'&&e.hasAttribute('checked');for(const a of [...e.attributes])e.removeAttribute(a.name);if(e.tagName==='INPUT'){e.type='checkbox';e.disabled=true;e.checked=checked;}if(href){e.title=href;e.setAttribute('aria-disabled','true');}}return doc.body.childNodes;}
function textViewer(text){const {bar,view,footer}=layout(),isMd=/\.(md|markdown)$/i.test(payload.name),isJson=/\.json$/i.test(payload.name);let raw=false,wrap=true;const mode=button('Source',()=>{raw=!raw;mode.textContent=raw?'Lecture':'Source';draw();}),wrapButton=button('Retour à la ligne',()=>{wrap=!wrap;wrapButton.setAttribute('aria-pressed',String(wrap));draw();});wrapButton.setAttribute('aria-pressed','true');if(isMd||isJson)bar.append(mode);bar.append(wrapButton);const find=input('Rechercher dans le texte');find.placeholder='Rechercher…';const result=node('small');result.setAttribute('role','status');bar.append(find,result);
 function draw(){view.replaceChildren();let shown=text;if(isJson&&!raw){try{shown=JSON.stringify(JSON.parse(text),null,2);}catch{result.textContent='JSON invalide · source affichée';}}const container=node(isMd&&!raw?'article':'pre',undefined,isMd&&!raw?'reader':'code'+(wrap?'':' nowrap'));if(isMd&&!raw)container.append(...safeMarkdown(shown));else container.textContent=shown;view.append(container);if(find.value){const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);let matches=0;const q=find.value.toLocaleLowerCase();for(const n of nodes){let start=0,index;const value=n.textContent,fragment=document.createDocumentFragment();while((index=value.toLocaleLowerCase().indexOf(q,start))>=0){fragment.append(document.createTextNode(value.slice(start,index)),node('mark',value.slice(index,index+q.length)));start=index+q.length;matches++;if(matches>=1000)break;}fragment.append(document.createTextNode(value.slice(start)));n.replaceWith(fragment);if(matches>=1000)break;}result.textContent=matches+(matches>=1000?'+':'')+' résultat'+(matches>1?'s':'');container.querySelector('mark')?.scrollIntoView({block:'center'});}else if(!isJson||raw)result.textContent='';meta(footer,text.split('\n').length+' lignes'+(payload.truncated?' · aperçu limité aux 500 000 premiers caractères':''));}
 find.addEventListener('input',draw);draw();}
function media(){const {bar,view,footer}=layout(),audio=payload.mime.startsWith('audio/'),media=node(audio?'audio':'video'),stage=node('div',undefined,'media-stage');media.controls=true;media.preload='metadata';media.src=url(new Blob([payload.buffer],{type:payload.mime}));if(audio)stage.append(node('span','♫','audio-mark'),node('p',payload.name));stage.append(media);view.append(stage);bar.append(button('−10 s',()=>media.currentTime=Math.max(0,media.currentTime-10)),button('+10 s',()=>media.currentTime=Math.min(media.duration||0,media.currentTime+10)),select('Vitesse de lecture',[['0.5','0,5×'],['0.75','0,75×'],['1','1×'],['1.25','1,25×'],['1.5','1,5×'],['2','2×']],'1',value=>media.playbackRate=Number(value)));const loop=button('Boucle',()=>{media.loop=!media.loop;loop.setAttribute('aria-pressed',String(media.loop));});loop.setAttribute('aria-pressed','false');bar.append(loop);media.addEventListener('loadedmetadata',()=>meta(footer,(audio?'Audio':media.videoWidth+' × '+media.videoHeight+' px')+' · '+Math.round(media.duration)+' s'));media.addEventListener('error',showError);}
addEventListener('message',async event=>{if(event.source!==parent||!event.data)return;if(event.data.type==='artifact-viewer-theme'){theme(event.data.colors);return;}if(event.data.type!=='artifact-viewer-init'||active||!(event.data.buffer instanceof ArrayBuffer))return;active=true;payload=event.data;theme(payload.colors);try{if(payload.kind==='pdf')await pdf();else if(payload.kind==='image')imageViewer();else if(payload.kind==='media')media();else{const decoded=new TextDecoder().decode(payload.buffer),text=decoded.slice(0,500000);payload.truncated=decoded.length>text.length;if(payload.kind==='csv')csv(text);else textViewer(text);}}catch{showError();}});
addEventListener('pagehide',()=>{objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];});
