#!/usr/bin/env python3
# SPDX-License-Identifier: Elastic-2.0

"""Render the two derived views of the surface inventory.

Both renderers are pure functions of the inventory document, so regenerating
them is byte-identical and `verify.py` can fail on a stale checked-in copy.

`README.md` is the human view. `restore-dependencies.json` is the machine view
`R0-10` consumes: the restore inputs, the order they are required in, and the
recovery objectives the drill measures itself against — so the drill reads a
dependency list rather than inventing one.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from tools.surface_inventory import model

README_SCHEMA_NOTE = (
    "GENERATED by `python3 tools/surface_inventory/verify.py --write` — do not "
    "edit by hand."
)
RESTORE_SCHEMA = "automonique.restore-dependencies/v1"
SOURCE_PATH = "plan/inventory/surface/inventory.json"


class RenderError(Exception):
    """The document cannot produce a derived view."""


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def owner_cell(entry: dict) -> str:
    if entry.get("owner"):
        return f"`{entry['owner']}`"
    return f"null ({entry.get('owner_gap')})"


def withheld_cell(entry: dict) -> str:
    shapes = [item["shape"] for item in entry.get("withheld") or []]
    return ", ".join(shapes) if shapes else "—"


def example_note(entry: dict) -> str:
    example = entry.get("example")
    if not isinstance(example, dict):
        return ""
    mark = "synthetic" if example["kind"] == "synthetic-placeholder" else "reserved"
    return f"; example `{example['value']}` ({mark})"


def quantity(value: Any, gap: Any) -> str:
    if value is None:
        return f"null ({gap})"
    return f"{value['value']} {value['unit']} (`{value['citation']}`)"


def detail_tenants(entry: dict) -> str:
    return (f"boundary class `{entry['class']}`" + example_note(entry)).lstrip("; ")


def detail_actor_mappings(entry: dict) -> str:
    return (f"{entry['external_source']} -> {entry['resolves_to']}; "
            f"confers role: no" + example_note(entry))


def detail_roles(entry: dict) -> str:
    return (f"authority {', '.join(entry['authority'])}; "
            f"assignment {entry['assignment']}")


def detail_credentials(entry: dict) -> str:
    return (f"rotation {entry['rotation']}; storage {entry['storage_class']}; "
            f"audience {entry['audience']}")


def detail_artifact_classes(entry: dict) -> str:
    retention = (f"`{entry['retention_ref']}`" if entry["retention_ref"]
                 else f"null ({entry['retention_gap']})")
    return f"visibility {entry['visibility']}; retention class {retention}"


def detail_workspaces(entry: dict) -> str:
    return (f"release promotability {entry['release_promotability']}"
            + example_note(entry))


def detail_retention(entry: dict) -> str:
    return (f"TTL {quantity(entry['ttl'], entry['ttl_gap'])}; "
            f"deletion {entry['deletion_method']}; "
            f"policy `{entry['governing_policy']}`")


def detail_budgets(entry: dict) -> str:
    return (f"limit {quantity(entry['limit'], entry['limit_gap'])}; "
            f"enforced at {entry['enforcement_point']}; "
            f"policy `{entry['governing_policy']}`")


def detail_backup(entry: dict) -> str:
    requires = ", ".join(f"`{name}`" for name in entry["requires"]) or "—"
    return f"verification {entry['verification']}; requires {requires}"


def detail_runbooks(entry: dict) -> str:
    production = "yes" if entry["production_touching"] else "no"
    return (f"trigger: {entry['trigger']}; reversibility {entry['reversibility']}; "
            f"{entry['procedure_status']}; touches production: {production}; "
            f"{len(entry['steps'])} executable step(s)")


DETAIL = {
    "tenants": detail_tenants,
    "actor_mappings": detail_actor_mappings,
    "roles": detail_roles,
    "credentials": detail_credentials,
    "artifact_classes": detail_artifact_classes,
    "workspaces_and_dirty_trees": detail_workspaces,
    "retention": detail_retention,
    "budgets": detail_budgets,
    "backup_dependencies": detail_backup,
    "runbooks": detail_runbooks,
}


def render_readme(document: dict[str, Any]) -> bytes:
    citations = document["citations"]
    measured = model.counts(document)
    lines: list[str] = [
        "# Identity, data and operations surface inventory",
        "",
        README_SCHEMA_NOTE,
        "",
        f"Source of truth: `{SOURCE_PATH}`. Checker: "
        f"`tools/surface_inventory/verify.py`.",
        "",
        "This is `R0-09`. It records the identity, data and operations surface "
        "the rewrite must carry as **classes, owners and shapes**. It resolves "
        "no secret, holds no credential value and grants no authorization.",
        "",
        "How to read it:",
        "",
        "- Every row cites a checked-in file and quotes it verbatim. The checker "
        "fails if the quoted words are not in the cited file, so a row can only "
        "say what this repository already says.",
        "- `null (reason)` is a measurement, not an omission. "
        "`unassigned-in-corpus` means the governing policy requires that field "
        "and no checked-in document assigns it — the gap is the finding. "
        "`not-reachable-from-repository` means the value lives in a running "
        "deployment a clean-room repository cannot reach.",
        "- A withheld fact is recorded as a shape and a reason and nothing else. "
        "Recording the shape of a private identifier is the point; recording the "
        "identifier would be the failure.",
        "- Runbook rows record that policy requires a runbook, its trigger and "
        "its reversibility. No step here is executable and none touches "
        "production.",
        "",
        "## Coverage",
        "",
        "| Section | Entries | Gaps | Owner unassigned | Withheld facts | "
        "Synthetic examples |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    totals = {"entries": 0, "gaps": 0, "owner_null": 0, "withheld": 0, "synthetic": 0}
    for name in model.SECTION_ORDER:
        row = measured[name]
        for key in totals:
            totals[key] += row[key]
        lines.append(
            f"| {model.SECTION_TITLES[name]} | {row['entries']} | {row['gaps']} | "
            f"{row['owner_null']} | {row['withheld']} | {row['synthetic']} |"
        )
    lines.append(
        f"| **total** | **{totals['entries']}** | **{totals['gaps']}** | "
        f"**{totals['owner_null']}** | **{totals['withheld']}** | "
        f"**{totals['synthetic']}** |"
    )

    for name in model.SECTION_ORDER:
        section = document["sections"][name]
        lines += ["", f"## {model.SECTION_TITLES[name]}", ""]
        if not section["entries"]:
            lines += [f"Empty: {section['empty_reason']}", ""]
        else:
            lines += [
                "| ID | Class | Owner | Detail | Withheld | Source |",
                "|---|---|---|---|---|---|",
            ]
            for entry in sorted(section["entries"], key=lambda e: e["id"]):
                source = citations[entry["citation"]]["path"]
                lines.append(
                    f"| `{entry['id']}` | {cell(entry['class'])} | "
                    f"{cell(owner_cell(entry))} | {cell(DETAIL[name](entry))} | "
                    f"{cell(withheld_cell(entry))} | `{source}` |"
                )
                lines.append(
                    f"| | | | {cell(entry['summary'])} | | |"
                )
        if section["gaps"]:
            lines += [
                "",
                "Gaps — what this section cannot record and why:",
                "",
                "| ID | Missing | Reason | Source |",
                "|---|---|---|---|",
            ]
            for gap in sorted(section["gaps"], key=lambda g: g["id"]):
                source = citations[gap["citation"]]["path"]
                lines.append(
                    f"| `{gap['id']}` | {cell(gap['missing'])} | {gap['reason']} | "
                    f"`{source}` |"
                )

    order, problems = model.restore_order(
        model.section_entries(document, "backup_dependencies"))
    if problems:
        raise RenderError("; ".join(problems))
    lines += [
        "",
        "## Restore order",
        "",
        "The order `R0-10` consumes, derived from the `requires` edges above and "
        "exported to `plan/inventory/surface/restore-dependencies.json`:",
        "",
    ]
    for position, name in enumerate(order, start=1):
        lines.append(f"{position}. `{name}`")

    lines += [
        "",
        "## Citations",
        "",
        "| ID | File |",
        "|---|---|",
    ]
    for name in sorted(citations):
        lines.append(f"| `{name}` | `{citations[name]['path']}` |")
    lines += [
        "",
        "## Owners",
        "",
        "| ID | Kind | Source |",
        "|---|---|---|",
    ]
    owners = document["owners"]
    for name in sorted(owners):
        source = citations[owners[name]["citation"]]["path"]
        lines.append(f"| `{name}` | {owners[name]['kind']} | `{source}` |")
    lines.append("")
    return ("\n".join(lines)).encode()


def render_restore(document: dict[str, Any], source_bytes: bytes) -> bytes:
    entries = model.section_entries(document, "backup_dependencies")
    order, problems = model.restore_order(entries)
    if problems:
        raise RenderError("; ".join(problems))
    by_id = {entry["id"]: entry for entry in entries}
    citations = document["citations"]

    objectives = []
    for entry in sorted(model.section_entries(document, "budgets"),
                        key=lambda e: e["id"]):
        if entry["class"] != "recovery-objective" or entry["limit"] is None:
            continue
        citation = citations[entry["limit"]["citation"]]
        objectives.append({
            "id": entry["id"],
            "summary": entry["summary"],
            "value": entry["limit"]["value"],
            "unit": entry["limit"]["unit"],
            "source": {"path": citation["path"], "quote": citation["quote"]},
        })
    if not objectives:
        raise RenderError(
            "no recovery objective carries a cited value, so R0-10 would have "
            "nothing to measure its drill against")

    document_out = {
        "schema": RESTORE_SCHEMA,
        "work_item": model.WORK_ITEM,
        "consumer": "R0-10",
        "source": {
            "path": SOURCE_PATH,
            "sha256": hashlib.sha256(source_bytes).hexdigest(),
        },
        "objectives": objectives,
        "order": [
            {
                "position": position,
                "id": name,
                "class": by_id[name]["class"],
                "requires": sorted(by_id[name]["requires"]),
                "verification": by_id[name]["verification"],
                "summary": by_id[name]["summary"],
            }
            for position, name in enumerate(order, start=1)
        ],
        "excluded": [
            {
                "id": entry["id"],
                "summary": entry["summary"],
                "source": citations[entry["citation"]]["path"],
            }
            for entry in sorted(entries, key=lambda e: e["id"])
            if entry["class"] == "excluded-material"
        ],
    }
    return (json.dumps(document_out, indent=2, ensure_ascii=True) + "\n").encode()
