# SPDX-License-Identifier: Elastic-2.0

[package]
name = "automonique-runner"
version = "0.1.0"
edition = "2024"
license = "Elastic-2.0"
publish = false

[dependencies]
automonique-protocol = { path = "../automonique-protocol" }
nix = { version = "=0.29.0", default-features = false, features = ["fs", "process", "signal", "user"] }
sha2 = "=0.10.9"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "forbid"
todo = "forbid"
unimplemented = "forbid"
