# SPDX-License-Identifier: Elastic-2.0

[package]
name = "automonique-runner"
version = "0.1.0"
edition = "2024"
license = "Elastic-2.0"
publish = false

[dependencies]
automonique-protocol = { path = "../automonique-protocol" }
landlock = { workspace = true }
seccompiler = { workspace = true }
nix = { version = "=0.29.0", default-features = false, features = ["fs", "poll", "process", "resource", "signal", "socket", "user"] }
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
