// SPDX-License-Identifier: Elastic-2.0

//! R1-11 verification contract: the TypeScript codegen spike.
//!
//! Each module corresponds to one row of the check table in
//! `plan/contracts/R1-11.md`. The spike's verdict is recorded in
//! `sdk/typescript/packages/protocol/generated/VERDICT.md`.
//!
//! Running this test regenerates `generated/spike.ts`. CI's zero-diff rule is
//! the reproducibility check: if regeneration changes the checked-in file, the
//! working tree is dirty and the plan workflow fails.

use std::path::PathBuf;
use std::process::Command;

use automonique_protocol::codegen::{SpikeSchema, emit_typescript, hostile_slice};

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn package_root() -> PathBuf {
    crate_root().join("../../../sdk/typescript/packages/protocol")
}

fn generated_path() -> PathBuf {
    package_root().join("generated/spike.ts")
}

fn javascript_runtime() -> Option<&'static str> {
    ["bun", "node"].into_iter().find(|candidate| {
        Command::new(candidate)
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
    })
}

/// Run `tsc` over one or more files, returning whether they typechecked.
fn typechecks(files: &[PathBuf]) -> Option<(bool, String)> {
    let mut command = Command::new("npx");
    command
        .arg("--offline")
        .arg("tsc")
        .arg("--noEmit")
        .arg("--strict")
        // Without this, tsc refuses with TS5112 whenever a tsconfig is present
        // and files are named on the command line. Every negative case would
        // then "fail" on a configuration error rather than the property it
        // guards, which is a vacuous pass.
        .arg("--ignoreConfig")
        .arg("--target")
        .arg("ES2023")
        .arg("--lib")
        .arg("ES2023,DOM")
        .arg("--module")
        .arg("ESNext")
        .arg("--moduleResolution")
        .arg("Bundler")
        .arg("--allowImportingTsExtensions")
        .args(files);
    let output = command.current_dir(package_root()).output().ok()?;
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    Some((output.status.success(), combined))
}

/// One run of the runtime half of the spike.
struct RuntimeRun {
    /// The interpreter that ran it.
    runtime: &'static str,
    /// Whether it exited zero.
    success: bool,
    /// What it printed on standard output.
    stdout: String,
    /// What it printed on standard error.
    stderr: String,
}

/// Run `conformance/spike-runtime.ts`, or `None` when no runtime is installed.
///
/// The output is returned rather than asserted on so that two checks can share
/// one execution: one asserts the script passed, the other reads the
/// measurements it printed.
fn run_runtime_conformance() -> Option<RuntimeRun> {
    let runtime = javascript_runtime()?;
    let output = Command::new(runtime)
        .arg(package_root().join("conformance/spike-runtime.ts"))
        .current_dir(package_root())
        .output()
        .ok()?;
    Some(RuntimeRun {
        runtime,
        success: output.status.success(),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
    })
}

mod source_direction {
    use super::*;

    #[test]
    fn the_generated_file_is_written_from_the_rust_slice() {
        let generated = emit_typescript(&hostile_slice());
        std::fs::create_dir_all(package_root().join("generated")).expect("generated directory");
        // Write atomically. `reproducibility::the_checked_in_file_matches_regeneration`
        // reads this file in the same parallel run, and a plain write left it
        // momentarily zero-length — a flake that turns a workspace run red for
        // reasons unrelated to the code under test.
        let final_path = generated_path();
        let staging = final_path.with_extension("ts.staging");
        std::fs::write(&staging, &generated).expect("stage generated file");
        std::fs::rename(&staging, &final_path).expect("publish generated file");

        assert!(generated.contains("GENERATED by automonique_protocol::codegen"));
        assert!(generated.contains("Rust is the wire source of truth"));
        assert!(generated.contains("readonly field: string;"));
        assert!(generated.contains("this.field = field;"));
        assert!(generated.contains("this.violation = violation;"));
        assert!(
            !generated.contains("constructor(readonly"),
            "parameter properties require a TypeScript transform and fail in Node strip-only mode"
        );
        // Nothing hand-written may redefine a wire structure; the marker above
        // is what a reviewer greps for.
        assert!(!generated.contains("TODO"));
    }
}

mod slice_difficulty {
    use super::*;

    #[test]
    fn the_slice_contains_every_construct_the_contract_demands() {
        let slice = hostile_slice();
        assert!(
            slice.branded_ids.len() >= 2,
            "two branded domains are required to test cross-assignment"
        );
        assert!(
            !slice.bounded_strings.is_empty(),
            "a bounded string is required"
        );
        assert!(
            !slice.bounded_integers.is_empty(),
            "a bounded integer is required"
        );

        let union = slice.unions.first().expect("a union is required");
        assert!(
            union.variants.len() >= 3,
            "three or more variants are required"
        );
        assert!(
            union
                .variants
                .iter()
                .any(|variant| variant.payload.is_none()),
            "a payload-free variant is required"
        );

        let sensitivities: Vec<_> = slice
            .enums
            .iter()
            .map(|generated| generated.sensitivity)
            .collect();
        assert_eq!(
            sensitivities.len(),
            2,
            "both enum classes are required: {sensitivities:?}"
        );
        assert_ne!(
            sensitivities[0], sensitivities[1],
            "the two enums must differ in sensitivity"
        );

        let generated = emit_typescript(&slice);
        // Optional versus nullable, and an event kind the generator has not seen.
        assert!(generated.contains("readonly note?: string;"));
        assert!(generated.contains("readonly detail: string | null;"));
        assert!(generated.contains("MAX_UNKNOWN_EVENT_BYTES"));
    }
}

mod reproducibility {
    use super::*;

    #[test]
    fn regeneration_is_byte_identical() {
        let first = emit_typescript(&hostile_slice());
        for _ in 0..8 {
            assert_eq!(
                emit_typescript(&hostile_slice()),
                first,
                "generation is not deterministic"
            );
        }
    }

    #[test]
    fn construction_order_does_not_change_the_output() {
        let forward = hostile_slice();
        let mut reversed = SpikeSchema {
            branded_ids: forward.branded_ids.clone(),
            bounded_strings: forward.bounded_strings.clone(),
            bounded_integers: forward.bounded_integers.clone(),
            unions: forward.unions.clone(),
            enums: forward.enums.clone(),
        };
        reversed.branded_ids.reverse();
        reversed.enums.reverse();
        for union in &mut reversed.unions {
            union.variants.reverse();
        }
        assert_eq!(
            emit_typescript(&reversed),
            emit_typescript(&forward),
            "output depends on input ordering"
        );
    }

    #[test]
    fn the_output_embeds_nothing_time_or_host_dependent() {
        let generated = emit_typescript(&hostile_slice());
        for forbidden in ["20", "generated at", "timestamp", "/home/", "Z\n"] {
            if forbidden == "20" {
                // A bare year prefix would appear in an embedded date; the
                // slice itself contains no such literal.
                assert!(
                    !generated.contains("2026-") && !generated.contains("2025-"),
                    "an embedded date reached the output"
                );
                continue;
            }
            assert!(
                !generated.to_lowercase().contains(forbidden),
                "output contains {forbidden:?}"
            );
        }
    }

    #[test]
    fn the_checked_in_file_matches_regeneration() {
        // The file is written by `source_direction`; this asserts the checked-in
        // copy equals what the generator produces, which is the zero-diff rule
        // CI enforces on the working tree.
        let expected = emit_typescript(&hostile_slice());
        let actual = std::fs::read_to_string(generated_path())
            .expect("the generated file is checked in — run this test to create it");
        assert_eq!(actual, expected, "the checked-in file is stale");
    }
}

mod typescript_properties {
    use super::*;

    #[test]
    fn the_generated_file_typechecks() {
        let Some((ok, output)) = typechecks(&[generated_path()]) else {
            eprintln!("GAP: tsc is unavailable; the codegen spike is unmeasured");
            return;
        };
        assert!(ok, "generated TypeScript does not typecheck:\n{output}");
    }

    /// The positive half of the negative cases.
    ///
    /// A file that fails to compile is evidence only when the same code
    /// compiles with the guarded property restored; otherwise a typo in an
    /// import path would look exactly like a preserved brand.
    /// `conformance/spike-runtime.ts` imports the same constructors from the
    /// same generated file and performs the same shape of assignment *within*
    /// one domain, so it must typecheck while `brand-crossing.ts` must not.
    /// Typechecking it also keeps the runtime measurements themselves under the
    /// compiler, which is where a stale cast would otherwise hide.
    #[test]
    fn the_runtime_conformance_script_typechecks() {
        let files = [
            package_root().join("conformance/spike-runtime.ts"),
            // The ambient `process` declaration the script relies on. The
            // package tsconfig picks it up by directory; a file list has to
            // name it.
            package_root().join("conformance/node-runtime.d.ts"),
        ];
        let Some((ok, output)) = typechecks(&files) else {
            eprintln!("GAP: tsc is unavailable; the runtime conformance script is unmeasured");
            return;
        };
        assert!(
            ok,
            "conformance/spike-runtime.ts does not typecheck:\n{output}"
        );
    }

    /// Each negative case must fail to compile, and fail for the property it
    /// guards. A case that fails on a configuration or import error proves
    /// nothing, so the expected diagnostic is named per file.
    #[test]
    fn every_negative_case_fails_for_its_own_reason() {
        let expected: [(&str, &str); 4] = [
            ("bound-widening.ts", "is not assignable to type 'TurnId'"),
            (
                "brand-crossing.ts",
                "Type 'TurnId' is not assignable to type 'SessionId'",
            ),
            (
                "payload-free-variant.ts",
                "Property 'text' does not exist on type",
            ),
            (
                "union-nonexhaustive.ts",
                "is not assignable to parameter of type 'never'",
            ),
        ];
        let directory = package_root().join("conformance/negative");
        let present: Vec<String> = std::fs::read_dir(&directory)
            .expect("negative cases are checked in")
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                (path.extension()?.to_str()? == "ts")
                    .then(|| path.file_name()?.to_str().map(str::to_owned))?
            })
            .collect();
        assert_eq!(
            present.len(),
            expected.len(),
            "a negative case was added or removed without updating the expectations: {present:?}"
        );

        for (file, diagnostic) in expected {
            let path = directory.join(file);
            let Some((ok, output)) = typechecks(&[path]) else {
                eprintln!("GAP: tsc is unavailable; negative cases are unmeasured");
                return;
            };
            assert!(!ok, "{file} compiled, so the property it guards was lost");
            assert!(
                output.contains(diagnostic),
                "{file} failed, but not for its own reason.\nexpected: {diagnostic}\nactual:\n{output}"
            );
        }
    }

    #[test]
    fn the_runtime_behaviour_matches_the_rust_bounds() {
        let Some(run) = run_runtime_conformance() else {
            eprintln!("GAP: no JavaScript runtime; runtime behaviour is unmeasured");
            return;
        };
        assert!(
            run.success,
            "runtime property check failed under {}:\n{}{}",
            run.runtime, run.stdout, run.stderr
        );
        println!(
            "codegen runtime checks under {}: {}",
            run.runtime,
            run.stdout.trim()
        );
    }
}

mod verdict_quality {
    use super::*;

    /// The properties the contract's check table names, spelled as the verdict
    /// tabulates them.
    const PROPERTIES: [&str; 5] = [
        "Bound preservation",
        "Brand distinctness",
        "Union exhaustiveness",
        "Unknown-event tolerance",
        "Reproducibility",
    ];

    /// The results a property row may record. `null` is the contract's spelling
    /// for unmeasured; anything else is a word whose meaning nobody has fixed,
    /// and a reader would have to guess whether it counts as a pass.
    const RECOGNIZED_RESULTS: [&str; 4] = ["pass", "partial", "fail", "null"];

    fn verdict() -> String {
        std::fs::read_to_string(package_root().join("generated/VERDICT.md"))
            .expect("the spike verdict is checked in")
    }

    /// The whole table row the verdict records for one property.
    fn row<'a>(verdict: &'a str, property: &str) -> &'a str {
        let prefix = format!("| {property} |");
        verdict
            .lines()
            .find(|line| line.starts_with(&prefix))
            .unwrap_or_else(|| panic!("the verdict has no table row for {property}"))
    }

    /// The Result column of that row.
    fn result_cell(verdict: &str, property: &str) -> String {
        row(verdict, property)
            .split('|')
            .nth(2)
            .unwrap_or_else(|| panic!("the {property} row has no result column"))
            .trim()
            .to_owned()
    }

    /// The section listing what `R8B` is told it must plan for.
    fn constraints(verdict: &str) -> &str {
        let start = verdict
            .find("## Constraints")
            .expect("the verdict lists the constraints R8B must plan for");
        let rest = &verdict[start..];
        &rest[..rest.find("\n## ").unwrap_or(rest.len())]
    }

    /// Where a generated brand exists.
    #[derive(Debug, Eq, PartialEq)]
    enum BrandExistence {
        /// The type checker knows which domain a value came from; the value
        /// itself does not.
        CompileTimeOnly,
        /// The value carries its domain into the running program.
        Runtime,
    }

    /// Read the emitted constructor for `name` and decide where its brand
    /// exists.
    ///
    /// What the verdict must record is derived from the emitter here rather
    /// than hard-coded, so that changing the emitter changes the obligation
    /// instead of leaving a stale caveat behind. A constructor that returns its
    /// argument unchanged cannot carry a brand: the value that comes out is the
    /// value that went in.
    fn brand_existence(generated: &str, name: &str) -> BrandExistence {
        let signature = format!("export function {name}(value: string): {name} {{");
        let start = generated
            .find(&signature)
            .unwrap_or_else(|| panic!("{name} has no emitted constructor"));
        let body = &generated[start + signature.len()..];
        let end = body
            .find("\n}")
            .unwrap_or_else(|| panic!("{name}'s emitted constructor is unterminated"));
        if body[..end].contains(&format!("return value as {name};")) {
            BrandExistence::CompileTimeOnly
        } else {
            BrandExistence::Runtime
        }
    }

    /// The branded domains whose brand exists only in the type checker.
    fn erasing_brands(generated: &str, slice: &SpikeSchema) -> Vec<String> {
        // Without this, a slice that lost its branded domains would make every
        // question below vacuously true rather than loudly wrong.
        assert!(
            !slice.branded_ids.is_empty(),
            "the slice has no branded domain to judge"
        );
        slice
            .branded_ids
            .iter()
            .filter(|id| brand_existence(generated, &id.name) == BrandExistence::CompileTimeOnly)
            .map(|id| id.name.clone())
            .collect()
    }

    #[test]
    fn the_verdict_is_recorded_and_names_its_outcome() {
        let verdict = verdict();
        let recognized = ["recommended with named constraints", "not recommended"]
            .iter()
            .any(|outcome| verdict.contains(outcome))
            || verdict.contains("**Verdict:** recommended");
        assert!(
            recognized,
            "the verdict does not state a recognized outcome"
        );
        // Every property in the contract's table must be accounted for, and
        // accounted for as a result rather than as prose.
        for property in PROPERTIES {
            let cell = result_cell(&verdict, property);
            assert!(
                RECOGNIZED_RESULTS.contains(&cell.as_str()),
                "{property} records {cell:?}, which is not one of {RECOGNIZED_RESULTS:?}"
            );
            // A qualification recorded only in the table is a footnote a
            // planner reads past. Anything short of a clean pass must also
            // reach the list of what R8B has to plan for.
            if cell != "pass" {
                let key = property
                    .split_whitespace()
                    .next()
                    .expect("a property name is not empty")
                    .to_lowercase();
                assert!(
                    constraints(&verdict).to_lowercase().contains(&key),
                    "{property} is recorded as {cell:?}, but no constraint mentions {key:?}"
                );
            }
        }
        assert!(
            verdict.contains("R8B"),
            "the verdict does not state what a failure would cost R8B"
        );
    }

    /// The contract calls a brand that holds at compile time and erases at
    /// runtime a partial pass. This is what stops the verdict from recording it
    /// as a clean one.
    #[test]
    fn a_brand_that_erases_at_runtime_is_recorded_as_a_partial() {
        let slice = hostile_slice();
        let generated = emit_typescript(&slice);
        let erasing = erasing_brands(&generated, &slice);
        if erasing.is_empty() {
            // The emitter now carries brands into the value, so there is no
            // partial left to record. The obligation follows the emitter.
            return;
        }

        let verdict = verdict();
        let cell = result_cell(&verdict, "Brand distinctness");
        assert_eq!(
            cell, "partial",
            "the brands of {erasing:?} exist only in the type checker, which the contract records \
             as a partial pass, but the verdict records {cell:?}"
        );
        let recorded = row(&verdict, "Brand distinctness").to_lowercase();
        assert!(
            recorded.contains("runtime") && recorded.contains("eras"),
            "the brand distinctness row is marked partial without naming the runtime erasure that \
             makes it one: {recorded}"
        );
        let planned = constraints(&verdict).to_lowercase();
        assert!(
            planned.contains("brand") && planned.contains("runtime"),
            "no constraint tells R8B what the runtime erasure costs it"
        );
    }

    /// What the verdict records, what the emitter writes and what the generated
    /// code actually does must be the same claim. The first two are text; this
    /// compares them against the third by running it.
    #[test]
    fn what_the_runtime_measures_agrees_with_the_emitted_brand() {
        let slice = hostile_slice();
        let generated = emit_typescript(&slice);
        let emitted = if erasing_brands(&generated, &slice).len() == slice.branded_ids.len() {
            "erased"
        } else {
            "carried"
        };
        let Some(run) = run_runtime_conformance() else {
            eprintln!("GAP: no JavaScript runtime; the brand's runtime existence is unmeasured");
            return;
        };
        let observed = run
            .stdout
            .lines()
            .find_map(|line| line.strip_prefix("brand-runtime-existence: "))
            .unwrap_or_else(|| {
                panic!(
                    "the runtime conformance script no longer reports whether the brand survives \
                     into the value:\n{}{}",
                    run.stdout, run.stderr
                )
            });
        assert_eq!(
            observed.trim(),
            emitted,
            "the emitted constructors say the brand is {emitted}, but running the generated code \
             under {} reports {observed}",
            run.runtime
        );
    }
}

/// The maintained read surface: the doctor report and the admin status read.
///
/// These files differ from `generated/spike.ts` in one way that matters. The
/// spike file is rewritten by an ordinary test run, so the check that it
/// matches the generator can never fail — the same run that compares it wrote
/// it. These files are only rewritten when `REGENERATE_ENV` is set, so the
/// comparison is a real gate: a hand edit, a stale checkout or a generator
/// change without a regeneration all turn the suite red.
mod maintained_surface {
    use std::collections::BTreeMap;
    use std::collections::BTreeSet;

    use automonique_protocol::admin::{
        AdminInstanceId, AdminResponse, DaemonState, DaemonStatus, MAX_ADMIN_CANONICAL_BYTES,
        MAX_INSTANCE_ID_BYTES, OperationalMetric, OperationalStatus, OperationalStatusParts,
    };
    use automonique_protocol::codec::RequestId;
    use automonique_protocol::codegen::{
        ADMIN_STATUS_MODULE, BARREL_MODULE, DOCTOR_MODULE, GENERATED_DIRECTORY, REGENERATE_COMMAND,
        REGENERATE_ENV, RUNTIME_MODULE, generated_files, maintained_modules, module_file_name,
    };
    use automonique_protocol::wire::{JsonValue, Message};
    use automonique_protocol::{
        MAX_DOCTOR_CHECKS, MAX_FINDING_CODE_BYTES, MAX_FINDING_MESSAGE_BYTES,
    };

    use super::*;

    fn generated_directory() -> PathBuf {
        package_root().join("generated")
    }

    fn files() -> BTreeMap<String, String> {
        generated_files().into_iter().collect()
    }

    /// The generated contents of one module, by stem.
    fn file(module: &str) -> String {
        let name = module_file_name(module);
        files()
            .remove(&name)
            .unwrap_or_else(|| panic!("{name} is not a generated file"))
    }

    /// Whether this run was asked to rewrite the checked-in files.
    fn regenerating() -> bool {
        std::env::var(REGENERATE_ENV).is_ok_and(|value| !value.is_empty() && value != "0")
    }

    /// The first place two texts diverge, named precisely enough to act on.
    fn first_difference(actual: &str, expected: &str) -> String {
        for (index, (left, right)) in actual.lines().zip(expected.lines()).enumerate() {
            if left != right {
                return format!("line {}: on disk {left:?}, generated {right:?}", index + 1);
            }
        }
        format!(
            "{} lines on disk, {} lines generated",
            actual.lines().count(),
            expected.lines().count()
        )
    }

    /// The field names one generated `_FIELDS` array carries, sorted.
    fn generated_fields(contents: &str, name: &str) -> Vec<String> {
        let marker = format!("export const {name}_FIELDS: readonly string[] = [\n");
        let start = contents
            .find(&marker)
            .unwrap_or_else(|| panic!("{name} has no generated field array"))
            + marker.len();
        let rest = &contents[start..];
        let end = rest
            .find("];")
            .unwrap_or_else(|| panic!("{name}'s generated field array is unterminated"));
        let mut names: Vec<String> = rest[..end]
            .lines()
            .filter_map(|line| {
                let trimmed = line.trim();
                Some(trimmed.strip_prefix('"')?.strip_suffix("\",")?.to_owned())
            })
            .collect();
        names.sort();
        names
    }

    /// A real encoded status message, built through the shipped constructors.
    ///
    /// The projection is required and its counts have to agree with the
    /// aggregate, so this is the smallest snapshot `to_message` will accept.
    fn encoded_status() -> Message {
        let status = DaemonStatus::new(
            AdminInstanceId::new("codegen-status").expect("valid instance"),
            DaemonState::Ready,
            7,
            41,
            2,
            3,
            1,
            true,
        )
        .expect("base status")
        .with_operational(
            OperationalStatus::new(OperationalStatusParts {
                observed_ms: 100,
                reconciliation_pending: 0,
                outbox_pending_ready: 2,
                outbox_pending_delayed: 1,
                outbox_in_flight_live: 4,
                outbox_in_flight_ambiguous: 0,
                outbox_delivered: 5,
                outbox_dead_lettered: 6,
                outbox_oldest_ready_age_ms: 7,
                telegram_pollers_live: 0,
                telegram_pollers_expired: 0,
                telegram_offset_lag: OperationalMetric::Unavailable,
                provider_available: OperationalMetric::Unavailable,
                sandbox_launch_refusals: OperationalMetric::Unavailable,
            })
            .expect("valid projection"),
        )
        .expect("coherent snapshot");
        AdminResponse::Status {
            request_id: RequestId::new("req-codegen-1").expect("valid request ID"),
            status,
        }
        .to_message()
        .expect("a complete status encodes")
    }

    /// The drift gate, and the regeneration that closes it.
    #[test]
    fn the_checked_in_files_match_regeneration() {
        let directory = generated_directory();
        let regenerating = regenerating();
        let mut stale = Vec::new();
        for (file_name, expected) in generated_files() {
            let path = directory.join(&file_name);
            if regenerating {
                std::fs::create_dir_all(&directory).expect("generated directory");
                // Publish atomically: the typecheck below reads these files in
                // the same parallel run, and a partial write would fail it for
                // a reason unrelated to the code under test.
                let staging = path.with_extension("ts.staging");
                std::fs::write(&staging, &expected).expect("stage generated file");
                std::fs::rename(&staging, &path).expect("publish generated file");
                continue;
            }
            match std::fs::read_to_string(&path) {
                Ok(actual) if actual == expected => {}
                Ok(actual) => stale.push(format!(
                    "{file_name}: {}",
                    first_difference(&actual, &expected)
                )),
                Err(error) => stale.push(format!("{file_name}: cannot be read ({error})")),
            }
        }
        assert!(
            stale.is_empty(),
            "the checked-in TypeScript in {GENERATED_DIRECTORY} no longer matches the generator:\
             \n  {}\n\nRegenerate with: {REGENERATE_COMMAND}",
            stale.join("\n  ")
        );
    }

    /// A module deleted from the generator must not leave its output behind.
    ///
    /// Without this, dropping a schema would pass every other check while a
    /// stale file kept serving the surface it described.
    #[test]
    fn the_generated_directory_holds_nothing_the_generator_does_not_own() {
        if regenerating() {
            // A regeneration is publishing into this directory from a test
            // running beside this one, so its contents are legitimately in
            // flux. The ordinary run — the one CI makes — is the measurement.
            eprintln!("GAP: skipped during regeneration; rerun without {REGENERATE_ENV}");
            return;
        }
        let owned: BTreeSet<String> = generated_files()
            .into_iter()
            .map(|(name, _)| name)
            .chain(std::iter::once("spike.ts".to_owned()))
            .collect();
        let present: BTreeSet<String> = std::fs::read_dir(generated_directory())
            .expect("the generated directory is checked in")
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                // `.ts` only: this skips `VERDICT.md` and the `.ts.staging`
                // file a concurrent regeneration may be holding open.
                (path.extension()?.to_str()? == "ts")
                    .then(|| path.file_name()?.to_str().map(str::to_owned))?
            })
            .collect();
        assert_eq!(
            present, owned,
            "{GENERATED_DIRECTORY} does not hold exactly the files the generator owns; \
             regenerate with: {REGENERATE_COMMAND}"
        );
    }

    #[test]
    fn regeneration_is_byte_identical() {
        let first = generated_files();
        for _ in 0..8 {
            assert_eq!(
                generated_files(),
                first,
                "generation of the maintained surface is not deterministic"
            );
        }
    }

    #[test]
    fn the_output_embeds_nothing_time_or_host_dependent() {
        for (file_name, contents) in generated_files() {
            for forbidden in ["generated at", "timestamp", "/home/", "2026-", "2025-"] {
                assert!(
                    !contents.to_lowercase().contains(forbidden),
                    "{file_name} contains {forbidden:?}"
                );
            }
        }
    }

    /// Every bound in the output is the Rust constant, not a number retyped
    /// next to it.
    ///
    /// The expected text is built from the constant itself, so changing
    /// `MAX_FINDING_MESSAGE_BYTES` and forgetting to regenerate fails here as
    /// well as at the drift gate.
    #[test]
    fn the_generated_bounds_are_the_rust_constants() {
        let doctor = file(DOCTOR_MODULE);
        let admin = file(ADMIN_STATUS_MODULE);
        for (file_name, contents, declaration) in [
            (
                DOCTOR_MODULE,
                &doctor,
                format!("export const FindingCode_MAX_BYTES = {MAX_FINDING_CODE_BYTES};"),
            ),
            (
                DOCTOR_MODULE,
                &doctor,
                format!("export const FindingMessage_MAX_BYTES = {MAX_FINDING_MESSAGE_BYTES};"),
            ),
            (
                DOCTOR_MODULE,
                &doctor,
                format!("export const MAX_DOCTOR_CHECKS = {MAX_DOCTOR_CHECKS};"),
            ),
            (
                ADMIN_STATUS_MODULE,
                &admin,
                format!("export const AdminInstanceId_MAX_BYTES = {MAX_INSTANCE_ID_BYTES};"),
            ),
            (
                ADMIN_STATUS_MODULE,
                &admin,
                format!("export const MAX_ADMIN_CANONICAL_BYTES = {MAX_ADMIN_CANONICAL_BYTES};"),
            ),
            (
                ADMIN_STATUS_MODULE,
                &admin,
                format!("export const WireCounter_MAX = {}n;", i64::MAX),
            ),
        ] {
            assert!(
                contents.contains(&declaration),
                "{file_name} does not carry the Rust bound: {declaration}"
            );
        }

        // Declaring the bound is not using it. A generator that emitted the
        // right constant and then compared against a different literal would
        // pass everything above.
        for (file_name, contents, name, max_bytes) in [
            (
                DOCTOR_MODULE,
                &doctor,
                "FindingCode",
                MAX_FINDING_CODE_BYTES,
            ),
            (
                DOCTOR_MODULE,
                &doctor,
                "FindingMessage",
                MAX_FINDING_MESSAGE_BYTES,
            ),
            (
                ADMIN_STATUS_MODULE,
                &admin,
                "AdminInstanceId",
                MAX_INSTANCE_ID_BYTES,
            ),
        ] {
            let check = format!(
                "  if (byteLength(value) > {max_bytes}) throw new ValidationError(\"{name}\", \
                 \"too_long\");"
            );
            assert!(
                contents.contains(&check),
                "{file_name} declares {name}'s bound but does not check it: {check}"
            );
        }
    }

    /// The closed value sets, restated here rather than read back from the
    /// generator.
    ///
    /// A generator that dropped a variant would agree with itself perfectly;
    /// this is the second opinion that catches it.
    #[test]
    fn every_closed_enumeration_carries_all_of_its_variants() {
        let expected: [(&str, &str, &[&str]); 5] = [
            (
                DOCTOR_MODULE,
                "CheckStatus",
                &["finding", "healthy", "unavailable"],
            ),
            (
                DOCTOR_MODULE,
                "ReportStatus",
                &["degraded", "failed", "healthy"],
            ),
            (
                ADMIN_STATUS_MODULE,
                "DaemonState",
                &["draining", "failed", "ready", "starting", "stopped"],
            ),
            (
                ADMIN_STATUS_MODULE,
                "ExecutionState",
                &["sandbox_enforceable_no_lane", "sandbox_unavailable_no_lane"],
            ),
            (
                ADMIN_STATUS_MODULE,
                "TelegramState",
                &["disabled_no_client", "lease_owned_no_client"],
            ),
        ];
        for (file_name, name, values) in expected {
            let contents = file(file_name);
            let literals: Vec<String> = values.iter().map(|value| format!("\"{value}\"")).collect();
            let declaration = format!("export type {name} = {};", literals.join(" | "));
            assert!(
                contents.contains(&declaration),
                "{file_name} lost a {name} variant.\nexpected: {declaration}"
            );
            let table = format!(
                "export const {name}_VALUES: readonly {name}[] = [{}];",
                literals.join(", ")
            );
            assert!(
                contents.contains(&table),
                "{file_name}'s {name} table does not match its type.\nexpected: {table}"
            );
            // Every one of these refuses an undefined spelling in Rust, so the
            // decoder must refuse it too rather than retain it.
            assert!(
                contents.contains(&format!(
                    "export function decode{name}(value: string): {name} {{"
                )),
                "{file_name} does not refuse an undefined {name}"
            );
        }
    }

    /// The unavailable arm is the one that must survive.
    ///
    /// `OperationalMetric` exists to stop a missing measurement from reading
    /// as a zero. A generated type that widened `value` to a plain counter
    /// would hand that mistake straight back to every client.
    #[test]
    fn the_operational_metric_union_keeps_its_unavailable_arm() {
        let admin = file(ADMIN_STATUS_MODULE);
        for arm in [
            "  | {readonly state: \"measured\"; readonly value: WireCounter}",
            "  | {readonly state: \"unavailable\"; readonly value: null}",
        ] {
            assert!(
                admin.contains(arm),
                "the OperationalMetric union lost an arm.\nexpected: {arm}"
            );
        }
        assert!(
            admin.contains("export function assertNeverOperationalMetric(value: never): never {"),
            "OperationalMetric has no exhaustiveness helper, so a dropped arm would go unnoticed \
             in TypeScript too"
        );
    }

    /// The generated field sets, measured against the encoder that produces the
    /// wire rather than against a list restated here.
    ///
    /// A list retyped in this file would only prove the generator agrees with
    /// my memory of `admin.rs`. Encoding a real [`DaemonStatus`] and reading
    /// the keys back compares the generated arrays with what the daemon
    /// actually sends, so a field added to the Rust body fails here on the
    /// next run instead of shipping a `_FIELDS` array the decoder would
    /// refuse.
    #[test]
    fn the_status_field_sets_are_the_encoders_own_field_sets() {
        let admin = file(ADMIN_STATUS_MODULE);
        let JsonValue::Object(body) = encoded_status().body().clone() else {
            panic!("a status message body is an object");
        };
        let keys = |entries: &[(String, JsonValue)]| -> Vec<String> {
            let mut names: Vec<String> = entries.iter().map(|(name, _)| name.clone()).collect();
            names.sort();
            names
        };

        assert_eq!(
            generated_fields(&admin, "DaemonStatus"),
            keys(&body),
            "the generated DaemonStatus field set is not what the admin encoder writes; \
             regenerate with: {REGENERATE_COMMAND}"
        );

        let Some(JsonValue::Object(operational)) = body
            .iter()
            .find(|(name, _)| name == "operational")
            .map(|(_, value)| value.clone())
        else {
            panic!("the status body carries an operational projection");
        };
        assert_eq!(
            generated_fields(&admin, "OperationalStatus"),
            keys(&operational),
            "the generated OperationalStatus field set is not what the admin encoder writes; \
             regenerate with: {REGENERATE_COMMAND}"
        );
    }

    /// Present-and-null is not the same fact as absent, and the status body
    /// carries exactly one field of the first kind.
    #[test]
    fn the_status_snapshot_keeps_nullable_apart_from_optional() {
        let admin = file(ADMIN_STATUS_MODULE);
        assert!(
            admin.contains("  readonly telegram_poller_epoch: WireCounter | null;"),
            "the nullable poller epoch lost its null"
        );
        assert!(
            admin.contains("  readonly operational: OperationalStatus;"),
            "the operational projection is required on the wire, not nullable"
        );
        assert!(
            !admin.contains("?:"),
            "no field of the status body may be absent; every key is required"
        );
    }

    /// The doctor report's own shapes.
    #[test]
    fn the_doctor_report_carries_its_bounded_reason() {
        let doctor = file(DOCTOR_MODULE);
        for declaration in [
            "  readonly code: FindingCode;",
            "  readonly message: FindingMessage;",
            "  readonly reason: DoctorReason | null;",
            "  readonly status: CheckStatus;",
            "  readonly checks: readonly DoctorCheck[];",
            "  readonly schema: typeof DOCTOR_REPORT_SCHEMA_V1;",
        ] {
            assert!(
                doctor.contains(declaration),
                "the doctor surface lost a declaration.\nexpected: {declaration}"
            );
        }
        // The grammars, not only the lengths. A code is lowercase and starts
        // with a letter; a message carries no control character.
        assert!(doctor.contains("export const FindingCode_PATTERN = /^[a-z][a-z0-9._-]*$/u;"));
        assert!(doctor.contains("export const FindingMessage_PATTERN = /^[^\\p{Cc}]+$/u;"));
    }

    /// The barrel must re-export every maintained module and not the spike.
    ///
    /// A module added to the generator but left out of the barrel would be
    /// generated, typechecked and unreachable — the failure mode that makes
    /// codegen look like it is working when nothing consumes it.
    #[test]
    fn the_barrel_reaches_every_maintained_module() {
        let name = module_file_name(BARREL_MODULE);
        let barrel = file(BARREL_MODULE);
        for module in maintained_modules() {
            let line = format!("export * from \"./{}\";", module.file_name);
            assert!(
                barrel.contains(&line),
                "{name} does not re-export {}, so nothing importing the package can reach \
                 it.\nexpected: {line}",
                module.file_name
            );
        }
        assert!(
            !barrel.contains("spike"),
            "the barrel re-exports the spike, whose own ValidationError collides with the \
             runtime module's"
        );
        // The barrel is a list of re-exports and nothing else; a declaration
        // here would be surface no schema describes.
        for line in barrel.lines() {
            assert!(
                line.is_empty() || line.starts_with("//") || line.starts_with("export * from "),
                "{name} carries something other than a re-export: {line:?}"
            );
        }
    }

    /// A generated file must say how to rewrite itself, and the command it
    /// names must be the one that works.
    #[test]
    fn every_generated_file_names_the_command_that_rewrites_it() {
        assert!(
            REGENERATE_COMMAND.contains(REGENERATE_ENV),
            "the documented regeneration command does not set the variable that triggers it"
        );
        for (file_name, contents) in generated_files() {
            assert!(
                contents.starts_with("// SPDX-License-Identifier: Apache-2.0\n"),
                "{file_name} does not open with the Apache-2.0 identifier the SDK tree requires"
            );
            assert!(
                !contents.contains("Elastic-2.0"),
                "{file_name} carries an Elastic-2.0 marker into the Apache-2.0 tree"
            );
            assert!(
                contents.contains(&format!("// Regenerate with: {REGENERATE_COMMAND}")),
                "{file_name} does not name the command that rewrites it"
            );
            assert!(
                contents.contains("GENERATED by automonique_protocol::codegen"),
                "{file_name} does not say it is generated"
            );
            assert!(
                !contents.contains("constructor(readonly"),
                "{file_name} uses a parameter property, which Node's strip-only loader rejects"
            );
            assert!(!contents.contains("TODO"), "{file_name} ships a TODO");
        }
    }

    /// Only the shared runtime file is hand-written prose; everything else is
    /// a description of a wire shape.
    #[test]
    fn only_the_shared_runtime_module_is_verbatim_typescript() {
        let mut seen_runtime = false;
        for module in maintained_modules() {
            if module.file_name == module_file_name(RUNTIME_MODULE) {
                seen_runtime = true;
                assert!(
                    !module.preamble.is_empty(),
                    "the runtime module lost the helpers every other module imports"
                );
                continue;
            }
            assert!(
                module.preamble.is_empty(),
                "{} smuggles hand-written TypeScript past the schema description",
                module.file_name
            );
        }
        assert!(
            seen_runtime,
            "no module provides the shared runtime helpers"
        );
    }

    /// The package's own tsconfig, over the whole package, generated files
    /// included. This is stricter than the flag set the spike's negative cases
    /// use: it turns on `exactOptionalPropertyTypes` and
    /// `noUncheckedIndexedAccess` as the SDK actually ships them.
    #[test]
    fn the_package_typechecks_with_the_generated_files() {
        let output = Command::new("npx")
            .arg("--offline")
            .arg("tsc")
            .arg("-p")
            .arg("./tsconfig.json")
            .current_dir(package_root())
            .output();
        let Ok(output) = output else {
            eprintln!("GAP: tsc is unavailable; the generated surface is untypechecked");
            return;
        };
        let combined = format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            output.status.success(),
            "the protocol package does not typecheck with the generated files:\n{combined}"
        );
    }
}
