// SPDX-License-Identifier: Elastic-2.0

//! R1-11 verification contract: the TypeScript codegen spike.
//!
//! Each module corresponds to one row of the check table in
//! `plan/contracts/R1-11.md`. The spike's verdict is recorded in
//! `sdk/typescript/packages/protocol/generated/VERDICT.md`.
//!
//! Running this test regenerates `generated/spike.ts`. CI's zero-diff rule is
//! the reproducibility check: if regeneration changes the checked-in file, the
//! working tree is dirty and the plan workflow fails.

use std::path::PathBuf;
use std::process::Command;

use automonique_protocol::codegen::{SpikeSchema, emit_typescript, hostile_slice};

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn package_root() -> PathBuf {
    crate_root().join("../../../sdk/typescript/packages/protocol")
}

fn generated_path() -> PathBuf {
    package_root().join("generated/spike.ts")
}

fn javascript_runtime() -> Option<&'static str> {
    ["bun", "node"].into_iter().find(|candidate| {
        Command::new(candidate)
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
    })
}

/// Run `tsc` over one file, returning whether it typechecked.
fn typechecks(file: &PathBuf) -> Option<(bool, String)> {
    let output = Command::new("npx")
        .arg("--offline")
        .arg("tsc")
        .arg("--noEmit")
        .arg("--strict")
        // Without this, tsc refuses with TS5112 whenever a tsconfig is present
        // and files are named on the command line. Every negative case would
        // then "fail" on a configuration error rather than the property it
        // guards, which is a vacuous pass.
        .arg("--ignoreConfig")
        .arg("--target")
        .arg("ES2023")
        .arg("--lib")
        .arg("ES2023,DOM")
        .arg("--module")
        .arg("ESNext")
        .arg("--moduleResolution")
        .arg("Bundler")
        .arg("--allowImportingTsExtensions")
        .arg(file)
        .current_dir(package_root())
        .output()
        .ok()?;
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    Some((output.status.success(), combined))
}

mod source_direction {
    use super::*;

    #[test]
    fn the_generated_file_is_written_from_the_rust_slice() {
        let generated = emit_typescript(&hostile_slice());
        std::fs::create_dir_all(package_root().join("generated")).expect("generated directory");
        std::fs::write(generated_path(), &generated).expect("write generated file");

        assert!(generated.contains("GENERATED by automonique_protocol::codegen"));
        assert!(generated.contains("Rust is the wire source of truth"));
        // Nothing hand-written may redefine a wire structure; the marker above
        // is what a reviewer greps for.
        assert!(!generated.contains("TODO"));
    }
}

mod slice_difficulty {
    use super::*;

    #[test]
    fn the_slice_contains_every_construct_the_contract_demands() {
        let slice = hostile_slice();
        assert!(
            slice.branded_ids.len() >= 2,
            "two branded domains are required to test cross-assignment"
        );
        assert!(
            !slice.bounded_strings.is_empty(),
            "a bounded string is required"
        );
        assert!(
            !slice.bounded_integers.is_empty(),
            "a bounded integer is required"
        );

        let union = slice.unions.first().expect("a union is required");
        assert!(
            union.variants.len() >= 3,
            "three or more variants are required"
        );
        assert!(
            union
                .variants
                .iter()
                .any(|variant| variant.payload.is_none()),
            "a payload-free variant is required"
        );

        let sensitivities: Vec<_> = slice
            .enums
            .iter()
            .map(|generated| generated.sensitivity)
            .collect();
        assert_eq!(
            sensitivities.len(),
            2,
            "both enum classes are required: {sensitivities:?}"
        );
        assert_ne!(
            sensitivities[0], sensitivities[1],
            "the two enums must differ in sensitivity"
        );

        let generated = emit_typescript(&slice);
        // Optional versus nullable, and an event kind the generator has not seen.
        assert!(generated.contains("readonly note?: string;"));
        assert!(generated.contains("readonly detail: string | null;"));
        assert!(generated.contains("MAX_UNKNOWN_EVENT_BYTES"));
    }
}

mod reproducibility {
    use super::*;

    #[test]
    fn regeneration_is_byte_identical() {
        let first = emit_typescript(&hostile_slice());
        for _ in 0..8 {
            assert_eq!(
                emit_typescript(&hostile_slice()),
                first,
                "generation is not deterministic"
            );
        }
    }

    #[test]
    fn construction_order_does_not_change_the_output() {
        let forward = hostile_slice();
        let mut reversed = SpikeSchema {
            branded_ids: forward.branded_ids.clone(),
            bounded_strings: forward.bounded_strings.clone(),
            bounded_integers: forward.bounded_integers.clone(),
            unions: forward.unions.clone(),
            enums: forward.enums.clone(),
        };
        reversed.branded_ids.reverse();
        reversed.enums.reverse();
        for union in &mut reversed.unions {
            union.variants.reverse();
        }
        assert_eq!(
            emit_typescript(&reversed),
            emit_typescript(&forward),
            "output depends on input ordering"
        );
    }

    #[test]
    fn the_output_embeds_nothing_time_or_host_dependent() {
        let generated = emit_typescript(&hostile_slice());
        for forbidden in ["20", "generated at", "timestamp", "/home/", "Z\n"] {
            if forbidden == "20" {
                // A bare year prefix would appear in an embedded date; the
                // slice itself contains no such literal.
                assert!(
                    !generated.contains("2026-") && !generated.contains("2025-"),
                    "an embedded date reached the output"
                );
                continue;
            }
            assert!(
                !generated.to_lowercase().contains(forbidden),
                "output contains {forbidden:?}"
            );
        }
    }

    #[test]
    fn the_checked_in_file_matches_regeneration() {
        // The file is written by `source_direction`; this asserts the checked-in
        // copy equals what the generator produces, which is the zero-diff rule
        // CI enforces on the working tree.
        let expected = emit_typescript(&hostile_slice());
        let actual = std::fs::read_to_string(generated_path())
            .expect("the generated file is checked in — run this test to create it");
        assert_eq!(actual, expected, "the checked-in file is stale");
    }
}

mod typescript_properties {
    use super::*;

    #[test]
    fn the_generated_file_typechecks() {
        let Some((ok, output)) = typechecks(&generated_path()) else {
            eprintln!("GAP: tsc is unavailable; the codegen spike is unmeasured");
            return;
        };
        assert!(ok, "generated TypeScript does not typecheck:\n{output}");
    }

    /// Each negative case must fail to compile, and fail for the property it
    /// guards. A case that fails on a configuration or import error proves
    /// nothing, so the expected diagnostic is named per file.
    #[test]
    fn every_negative_case_fails_for_its_own_reason() {
        let expected: [(&str, &str); 4] = [
            ("bound-widening.ts", "is not assignable to type 'TurnId'"),
            (
                "brand-crossing.ts",
                "Type 'TurnId' is not assignable to type 'SessionId'",
            ),
            (
                "payload-free-variant.ts",
                "Property 'text' does not exist on type",
            ),
            (
                "union-nonexhaustive.ts",
                "is not assignable to parameter of type 'never'",
            ),
        ];
        let directory = package_root().join("conformance/negative");
        let present: Vec<String> = std::fs::read_dir(&directory)
            .expect("negative cases are checked in")
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                (path.extension()?.to_str()? == "ts")
                    .then(|| path.file_name()?.to_str().map(str::to_owned))?
            })
            .collect();
        assert_eq!(
            present.len(),
            expected.len(),
            "a negative case was added or removed without updating the expectations: {present:?}"
        );

        for (file, diagnostic) in expected {
            let path = directory.join(file);
            let Some((ok, output)) = typechecks(&path) else {
                eprintln!("GAP: tsc is unavailable; negative cases are unmeasured");
                return;
            };
            assert!(!ok, "{file} compiled, so the property it guards was lost");
            assert!(
                output.contains(diagnostic),
                "{file} failed, but not for its own reason.\nexpected: {diagnostic}\nactual:\n{output}"
            );
        }
    }

    #[test]
    fn the_runtime_behaviour_matches_the_rust_bounds() {
        let Some(runtime) = javascript_runtime() else {
            eprintln!("GAP: no JavaScript runtime; runtime behaviour is unmeasured");
            return;
        };
        let script = package_root().join("conformance/spike-runtime.ts");
        let output = Command::new(runtime)
            .arg(&script)
            .current_dir(package_root())
            .output()
            .expect("runtime check starts");
        assert!(
            output.status.success(),
            "runtime property check failed under {runtime}:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        println!(
            "codegen runtime checks under {runtime}: {}",
            String::from_utf8_lossy(&output.stdout).trim()
        );
    }
}

mod verdict_quality {
    use super::*;

    #[test]
    fn the_verdict_is_recorded_and_names_its_outcome() {
        let verdict = std::fs::read_to_string(package_root().join("generated/VERDICT.md"))
            .expect("the spike verdict is checked in");
        let recognized = ["recommended with named constraints", "not recommended"]
            .iter()
            .any(|outcome| verdict.contains(outcome))
            || verdict.contains("**Verdict:** recommended");
        assert!(
            recognized,
            "the verdict does not state a recognized outcome"
        );
        // Every property in the contract's table must be accounted for.
        for property in [
            "bound preservation",
            "brand distinctness",
            "union exhaustiveness",
            "unknown-event tolerance",
            "reproducibility",
        ] {
            assert!(
                verdict.to_lowercase().contains(property),
                "the verdict does not account for {property}"
            );
        }
        assert!(
            verdict.contains("R8B"),
            "the verdict does not state what a failure would cost R8B"
        );
    }
}
