// SPDX-License-Identifier: Elastic-2.0

//! R1-11 verification contract: the TypeScript codegen spike.
//!
//! Each module corresponds to one row of the check table in
//! `plan/contracts/R1-11.md`. The spike's verdict is recorded in
//! `sdk/typescript/packages/protocol/generated/VERDICT.md`.
//!
//! Running this test regenerates `generated/spike.ts`. CI's zero-diff rule is
//! the reproducibility check: if regeneration changes the checked-in file, the
//! working tree is dirty and the plan workflow fails.

use std::path::PathBuf;
use std::process::Command;

use automonique_protocol::codegen::{SpikeSchema, emit_typescript, hostile_slice};

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn package_root() -> PathBuf {
    crate_root().join("../../../sdk/typescript/packages/protocol")
}

fn generated_path() -> PathBuf {
    package_root().join("generated/spike.ts")
}

fn javascript_runtime() -> Option<&'static str> {
    ["bun", "node"].into_iter().find(|candidate| {
        Command::new(candidate)
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
    })
}

/// Run `tsc` over one or more files, returning whether they typechecked.
fn typechecks(files: &[PathBuf]) -> Option<(bool, String)> {
    let mut command = Command::new("npx");
    command
        .arg("--offline")
        .arg("tsc")
        .arg("--noEmit")
        .arg("--strict")
        // Without this, tsc refuses with TS5112 whenever a tsconfig is present
        // and files are named on the command line. Every negative case would
        // then "fail" on a configuration error rather than the property it
        // guards, which is a vacuous pass.
        .arg("--ignoreConfig")
        .arg("--target")
        .arg("ES2023")
        .arg("--lib")
        .arg("ES2023,DOM")
        .arg("--module")
        .arg("ESNext")
        .arg("--moduleResolution")
        .arg("Bundler")
        .arg("--allowImportingTsExtensions")
        .args(files);
    let output = command.current_dir(package_root()).output().ok()?;
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    Some((output.status.success(), combined))
}

/// One run of the runtime half of the spike.
struct RuntimeRun {
    /// The interpreter that ran it.
    runtime: &'static str,
    /// Whether it exited zero.
    success: bool,
    /// What it printed on standard output.
    stdout: String,
    /// What it printed on standard error.
    stderr: String,
}

/// Run `conformance/spike-runtime.ts`, or `None` when no runtime is installed.
///
/// The output is returned rather than asserted on so that two checks can share
/// one execution: one asserts the script passed, the other reads the
/// measurements it printed.
fn run_runtime_conformance() -> Option<RuntimeRun> {
    let runtime = javascript_runtime()?;
    let output = Command::new(runtime)
        .arg(package_root().join("conformance/spike-runtime.ts"))
        .current_dir(package_root())
        .output()
        .ok()?;
    Some(RuntimeRun {
        runtime,
        success: output.status.success(),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
    })
}

mod source_direction {
    use super::*;

    #[test]
    fn the_generated_file_is_written_from_the_rust_slice() {
        let generated = emit_typescript(&hostile_slice());
        std::fs::create_dir_all(package_root().join("generated")).expect("generated directory");
        // Write atomically. `reproducibility::the_checked_in_file_matches_regeneration`
        // reads this file in the same parallel run, and a plain write left it
        // momentarily zero-length — a flake that turns a workspace run red for
        // reasons unrelated to the code under test.
        let final_path = generated_path();
        let staging = final_path.with_extension("ts.staging");
        std::fs::write(&staging, &generated).expect("stage generated file");
        std::fs::rename(&staging, &final_path).expect("publish generated file");

        assert!(generated.contains("GENERATED by automonique_protocol::codegen"));
        assert!(generated.contains("Rust is the wire source of truth"));
        // Nothing hand-written may redefine a wire structure; the marker above
        // is what a reviewer greps for.
        assert!(!generated.contains("TODO"));
    }
}

mod slice_difficulty {
    use super::*;

    #[test]
    fn the_slice_contains_every_construct_the_contract_demands() {
        let slice = hostile_slice();
        assert!(
            slice.branded_ids.len() >= 2,
            "two branded domains are required to test cross-assignment"
        );
        assert!(
            !slice.bounded_strings.is_empty(),
            "a bounded string is required"
        );
        assert!(
            !slice.bounded_integers.is_empty(),
            "a bounded integer is required"
        );

        let union = slice.unions.first().expect("a union is required");
        assert!(
            union.variants.len() >= 3,
            "three or more variants are required"
        );
        assert!(
            union
                .variants
                .iter()
                .any(|variant| variant.payload.is_none()),
            "a payload-free variant is required"
        );

        let sensitivities: Vec<_> = slice
            .enums
            .iter()
            .map(|generated| generated.sensitivity)
            .collect();
        assert_eq!(
            sensitivities.len(),
            2,
            "both enum classes are required: {sensitivities:?}"
        );
        assert_ne!(
            sensitivities[0], sensitivities[1],
            "the two enums must differ in sensitivity"
        );

        let generated = emit_typescript(&slice);
        // Optional versus nullable, and an event kind the generator has not seen.
        assert!(generated.contains("readonly note?: string;"));
        assert!(generated.contains("readonly detail: string | null;"));
        assert!(generated.contains("MAX_UNKNOWN_EVENT_BYTES"));
    }
}

mod reproducibility {
    use super::*;

    #[test]
    fn regeneration_is_byte_identical() {
        let first = emit_typescript(&hostile_slice());
        for _ in 0..8 {
            assert_eq!(
                emit_typescript(&hostile_slice()),
                first,
                "generation is not deterministic"
            );
        }
    }

    #[test]
    fn construction_order_does_not_change_the_output() {
        let forward = hostile_slice();
        let mut reversed = SpikeSchema {
            branded_ids: forward.branded_ids.clone(),
            bounded_strings: forward.bounded_strings.clone(),
            bounded_integers: forward.bounded_integers.clone(),
            unions: forward.unions.clone(),
            enums: forward.enums.clone(),
        };
        reversed.branded_ids.reverse();
        reversed.enums.reverse();
        for union in &mut reversed.unions {
            union.variants.reverse();
        }
        assert_eq!(
            emit_typescript(&reversed),
            emit_typescript(&forward),
            "output depends on input ordering"
        );
    }

    #[test]
    fn the_output_embeds_nothing_time_or_host_dependent() {
        let generated = emit_typescript(&hostile_slice());
        for forbidden in ["20", "generated at", "timestamp", "/home/", "Z\n"] {
            if forbidden == "20" {
                // A bare year prefix would appear in an embedded date; the
                // slice itself contains no such literal.
                assert!(
                    !generated.contains("2026-") && !generated.contains("2025-"),
                    "an embedded date reached the output"
                );
                continue;
            }
            assert!(
                !generated.to_lowercase().contains(forbidden),
                "output contains {forbidden:?}"
            );
        }
    }

    #[test]
    fn the_checked_in_file_matches_regeneration() {
        // The file is written by `source_direction`; this asserts the checked-in
        // copy equals what the generator produces, which is the zero-diff rule
        // CI enforces on the working tree.
        let expected = emit_typescript(&hostile_slice());
        let actual = std::fs::read_to_string(generated_path())
            .expect("the generated file is checked in — run this test to create it");
        assert_eq!(actual, expected, "the checked-in file is stale");
    }
}

mod typescript_properties {
    use super::*;

    #[test]
    fn the_generated_file_typechecks() {
        let Some((ok, output)) = typechecks(&[generated_path()]) else {
            eprintln!("GAP: tsc is unavailable; the codegen spike is unmeasured");
            return;
        };
        assert!(ok, "generated TypeScript does not typecheck:\n{output}");
    }

    /// The positive half of the negative cases.
    ///
    /// A file that fails to compile is evidence only when the same code
    /// compiles with the guarded property restored; otherwise a typo in an
    /// import path would look exactly like a preserved brand.
    /// `conformance/spike-runtime.ts` imports the same constructors from the
    /// same generated file and performs the same shape of assignment *within*
    /// one domain, so it must typecheck while `brand-crossing.ts` must not.
    /// Typechecking it also keeps the runtime measurements themselves under the
    /// compiler, which is where a stale cast would otherwise hide.
    #[test]
    fn the_runtime_conformance_script_typechecks() {
        let files = [
            package_root().join("conformance/spike-runtime.ts"),
            // The ambient `process` declaration the script relies on. The
            // package tsconfig picks it up by directory; a file list has to
            // name it.
            package_root().join("conformance/node-runtime.d.ts"),
        ];
        let Some((ok, output)) = typechecks(&files) else {
            eprintln!("GAP: tsc is unavailable; the runtime conformance script is unmeasured");
            return;
        };
        assert!(
            ok,
            "conformance/spike-runtime.ts does not typecheck:\n{output}"
        );
    }

    /// Each negative case must fail to compile, and fail for the property it
    /// guards. A case that fails on a configuration or import error proves
    /// nothing, so the expected diagnostic is named per file.
    #[test]
    fn every_negative_case_fails_for_its_own_reason() {
        let expected: [(&str, &str); 4] = [
            ("bound-widening.ts", "is not assignable to type 'TurnId'"),
            (
                "brand-crossing.ts",
                "Type 'TurnId' is not assignable to type 'SessionId'",
            ),
            (
                "payload-free-variant.ts",
                "Property 'text' does not exist on type",
            ),
            (
                "union-nonexhaustive.ts",
                "is not assignable to parameter of type 'never'",
            ),
        ];
        let directory = package_root().join("conformance/negative");
        let present: Vec<String> = std::fs::read_dir(&directory)
            .expect("negative cases are checked in")
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                (path.extension()?.to_str()? == "ts")
                    .then(|| path.file_name()?.to_str().map(str::to_owned))?
            })
            .collect();
        assert_eq!(
            present.len(),
            expected.len(),
            "a negative case was added or removed without updating the expectations: {present:?}"
        );

        for (file, diagnostic) in expected {
            let path = directory.join(file);
            let Some((ok, output)) = typechecks(&[path]) else {
                eprintln!("GAP: tsc is unavailable; negative cases are unmeasured");
                return;
            };
            assert!(!ok, "{file} compiled, so the property it guards was lost");
            assert!(
                output.contains(diagnostic),
                "{file} failed, but not for its own reason.\nexpected: {diagnostic}\nactual:\n{output}"
            );
        }
    }

    #[test]
    fn the_runtime_behaviour_matches_the_rust_bounds() {
        let Some(run) = run_runtime_conformance() else {
            eprintln!("GAP: no JavaScript runtime; runtime behaviour is unmeasured");
            return;
        };
        assert!(
            run.success,
            "runtime property check failed under {}:\n{}{}",
            run.runtime, run.stdout, run.stderr
        );
        println!(
            "codegen runtime checks under {}: {}",
            run.runtime,
            run.stdout.trim()
        );
    }
}

mod verdict_quality {
    use super::*;

    /// The properties the contract's check table names, spelled as the verdict
    /// tabulates them.
    const PROPERTIES: [&str; 5] = [
        "Bound preservation",
        "Brand distinctness",
        "Union exhaustiveness",
        "Unknown-event tolerance",
        "Reproducibility",
    ];

    /// The results a property row may record. `null` is the contract's spelling
    /// for unmeasured; anything else is a word whose meaning nobody has fixed,
    /// and a reader would have to guess whether it counts as a pass.
    const RECOGNIZED_RESULTS: [&str; 4] = ["pass", "partial", "fail", "null"];

    fn verdict() -> String {
        std::fs::read_to_string(package_root().join("generated/VERDICT.md"))
            .expect("the spike verdict is checked in")
    }

    /// The whole table row the verdict records for one property.
    fn row<'a>(verdict: &'a str, property: &str) -> &'a str {
        let prefix = format!("| {property} |");
        verdict
            .lines()
            .find(|line| line.starts_with(&prefix))
            .unwrap_or_else(|| panic!("the verdict has no table row for {property}"))
    }

    /// The Result column of that row.
    fn result_cell(verdict: &str, property: &str) -> String {
        row(verdict, property)
            .split('|')
            .nth(2)
            .unwrap_or_else(|| panic!("the {property} row has no result column"))
            .trim()
            .to_owned()
    }

    /// The section listing what `R8B` is told it must plan for.
    fn constraints(verdict: &str) -> &str {
        let start = verdict
            .find("## Constraints")
            .expect("the verdict lists the constraints R8B must plan for");
        let rest = &verdict[start..];
        &rest[..rest.find("\n## ").unwrap_or(rest.len())]
    }

    /// Where a generated brand exists.
    #[derive(Debug, Eq, PartialEq)]
    enum BrandExistence {
        /// The type checker knows which domain a value came from; the value
        /// itself does not.
        CompileTimeOnly,
        /// The value carries its domain into the running program.
        Runtime,
    }

    /// Read the emitted constructor for `name` and decide where its brand
    /// exists.
    ///
    /// What the verdict must record is derived from the emitter here rather
    /// than hard-coded, so that changing the emitter changes the obligation
    /// instead of leaving a stale caveat behind. A constructor that returns its
    /// argument unchanged cannot carry a brand: the value that comes out is the
    /// value that went in.
    fn brand_existence(generated: &str, name: &str) -> BrandExistence {
        let signature = format!("export function {name}(value: string): {name} {{");
        let start = generated
            .find(&signature)
            .unwrap_or_else(|| panic!("{name} has no emitted constructor"));
        let body = &generated[start + signature.len()..];
        let end = body
            .find("\n}")
            .unwrap_or_else(|| panic!("{name}'s emitted constructor is unterminated"));
        if body[..end].contains(&format!("return value as {name};")) {
            BrandExistence::CompileTimeOnly
        } else {
            BrandExistence::Runtime
        }
    }

    /// The branded domains whose brand exists only in the type checker.
    fn erasing_brands(generated: &str, slice: &SpikeSchema) -> Vec<String> {
        // Without this, a slice that lost its branded domains would make every
        // question below vacuously true rather than loudly wrong.
        assert!(
            !slice.branded_ids.is_empty(),
            "the slice has no branded domain to judge"
        );
        slice
            .branded_ids
            .iter()
            .filter(|id| brand_existence(generated, &id.name) == BrandExistence::CompileTimeOnly)
            .map(|id| id.name.clone())
            .collect()
    }

    #[test]
    fn the_verdict_is_recorded_and_names_its_outcome() {
        let verdict = verdict();
        let recognized = ["recommended with named constraints", "not recommended"]
            .iter()
            .any(|outcome| verdict.contains(outcome))
            || verdict.contains("**Verdict:** recommended");
        assert!(
            recognized,
            "the verdict does not state a recognized outcome"
        );
        // Every property in the contract's table must be accounted for, and
        // accounted for as a result rather than as prose.
        for property in PROPERTIES {
            let cell = result_cell(&verdict, property);
            assert!(
                RECOGNIZED_RESULTS.contains(&cell.as_str()),
                "{property} records {cell:?}, which is not one of {RECOGNIZED_RESULTS:?}"
            );
            // A qualification recorded only in the table is a footnote a
            // planner reads past. Anything short of a clean pass must also
            // reach the list of what R8B has to plan for.
            if cell != "pass" {
                let key = property
                    .split_whitespace()
                    .next()
                    .expect("a property name is not empty")
                    .to_lowercase();
                assert!(
                    constraints(&verdict).to_lowercase().contains(&key),
                    "{property} is recorded as {cell:?}, but no constraint mentions {key:?}"
                );
            }
        }
        assert!(
            verdict.contains("R8B"),
            "the verdict does not state what a failure would cost R8B"
        );
    }

    /// The contract calls a brand that holds at compile time and erases at
    /// runtime a partial pass. This is what stops the verdict from recording it
    /// as a clean one.
    #[test]
    fn a_brand_that_erases_at_runtime_is_recorded_as_a_partial() {
        let slice = hostile_slice();
        let generated = emit_typescript(&slice);
        let erasing = erasing_brands(&generated, &slice);
        if erasing.is_empty() {
            // The emitter now carries brands into the value, so there is no
            // partial left to record. The obligation follows the emitter.
            return;
        }

        let verdict = verdict();
        let cell = result_cell(&verdict, "Brand distinctness");
        assert_eq!(
            cell, "partial",
            "the brands of {erasing:?} exist only in the type checker, which the contract records \
             as a partial pass, but the verdict records {cell:?}"
        );
        let recorded = row(&verdict, "Brand distinctness").to_lowercase();
        assert!(
            recorded.contains("runtime") && recorded.contains("eras"),
            "the brand distinctness row is marked partial without naming the runtime erasure that \
             makes it one: {recorded}"
        );
        let planned = constraints(&verdict).to_lowercase();
        assert!(
            planned.contains("brand") && planned.contains("runtime"),
            "no constraint tells R8B what the runtime erasure costs it"
        );
    }

    /// What the verdict records, what the emitter writes and what the generated
    /// code actually does must be the same claim. The first two are text; this
    /// compares them against the third by running it.
    #[test]
    fn what_the_runtime_measures_agrees_with_the_emitted_brand() {
        let slice = hostile_slice();
        let generated = emit_typescript(&slice);
        let emitted = if erasing_brands(&generated, &slice).len() == slice.branded_ids.len() {
            "erased"
        } else {
            "carried"
        };
        let Some(run) = run_runtime_conformance() else {
            eprintln!("GAP: no JavaScript runtime; the brand's runtime existence is unmeasured");
            return;
        };
        let observed = run
            .stdout
            .lines()
            .find_map(|line| line.strip_prefix("brand-runtime-existence: "))
            .unwrap_or_else(|| {
                panic!(
                    "the runtime conformance script no longer reports whether the brand survives \
                     into the value:\n{}{}",
                    run.stdout, run.stderr
                )
            });
        assert_eq!(
            observed.trim(),
            emitted,
            "the emitted constructors say the brand is {emitted}, but running the generated code \
             under {} reports {observed}",
            run.runtime
        );
    }
}
