# SPDX-License-Identifier: Elastic-2.0

[package]
name = "automonique-agents"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
automonique-connector-substrate = { path = "../automonique-connector-substrate" }
automonique-runner = { path = "../automonique-runner" }
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
